/**
 * Generates two files from src/lib/db/schema.sqlite.ts, where tables are
 * authored:
 *
 * - src/lib/db/schema.ts, the module the application imports
 *   (`@/src/lib/db/schema`). It exports every table, typed as the SQLite
 *   table, and picks the dialect's tables (getDialect()) at module load.
 * - src/lib/db/schema.pg.ts, the same tables for PostgreSQL: pgTable,
 *   boolean() for boolean-mode integers, identity columns for AUTOINCREMENT
 *   keys, integer or bigint({ mode: "number" }) for the other integers as
 *   src/lib/db/pg-column-types.ts classifies them, coalesce() for ifnull(),
 *   and no .references() (foreign keys are not enforced on SQLite either).
 *
 * The transform edits the source text in place, so comments and layout carry
 * over unchanged, and the output depends on nothing but the two input files.
 * Anything the transform does not know fails with the file position, so a new
 * schema construct is translated on purpose rather than by accident.
 *
 * Usage:
 *   bun run db:generate-pg-schema   writes both files
 *   bun run db:check-pg-schema      exits 1 when either file is stale
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { PG_INTEGER_COLUMNS, type PgIntegerType } from "../../src/lib/db/pg-column-types";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

export const SOURCE_PATH = "src/lib/db/schema.sqlite.ts";
export const SWITCH_PATH = "src/lib/db/schema.ts";
export const PG_PATH = "src/lib/db/schema.pg.ts";

const GENERATED_NOTICE = "// Generated by scripts/db/generate-pg-schema.ts from schema.sqlite.ts; do not edit.";

/** The drizzle-orm/sqlite-core imports the transform knows how to translate. */
const SUPPORTED_SQLITE_IMPORTS = new Set(["sqliteTable", "integer", "text", "index", "uniqueIndex"]);

/** SQLite functions inside sql`` the transform has no PostgreSQL translation for. */
const UNTRANSLATED_SQL =
  /\b(json_each|json_valid|json_extract|json_group_array|json_group_object|strftime|julianday|unixepoch|datetime|glob|last_insert_rowid|rowid|group_concat|iif|printf|nocase)\b/i;

export type IntegerClassification = Readonly<Record<string, Readonly<Record<string, PgIntegerType>>>>;

export type GeneratedFile = { path: string; content: string };

type Edit = { start: number; end: number; text: string };

class SchemaTransformError extends Error {}

function position(sourceFile: ts.SourceFile, node: ts.Node): string {
  const { line, character } = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
  return `${sourceFile.fileName}:${line + 1}:${character + 1}`;
}

function fail(sourceFile: ts.SourceFile, node: ts.Node, message: string): never {
  throw new SchemaTransformError(`${position(sourceFile, node)}: ${message}`);
}

function parse(sourceText: string, fileName: string): ts.SourceFile {
  return ts.createSourceFile(fileName, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
}

function hasExportModifier(node: ts.Node): boolean {
  return ts.canHaveModifiers(node) && (ts.getModifiers(node) ?? []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
}

function isCallTo(node: ts.Node, name: string): node is ts.CallExpression {
  return ts.isCallExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === name;
}

function stringArgument(sourceFile: ts.SourceFile, call: ts.CallExpression, what: string): string {
  const first = call.arguments[0];
  if (!first || !ts.isStringLiteralLike(first)) fail(sourceFile, call, `${what} needs an explicit name as its first argument`);
  return first.text;
}

/** The properties of an object literal as name -> value source text; fails on anything but plain properties. */
function objectProperties(sourceFile: ts.SourceFile, node: ts.Expression): Map<string, string> {
  if (!ts.isObjectLiteralExpression(node)) fail(sourceFile, node, "expected an object literal");
  const properties = new Map<string, string>();
  for (const property of node.properties) {
    if (!ts.isPropertyAssignment(property) || !(ts.isIdentifier(property.name) || ts.isStringLiteral(property.name))) {
      fail(sourceFile, property, "expected a plain property");
    }
    // String values in double quotes whatever the source used, so callers compare one spelling.
    const value = property.initializer;
    properties.set(property.name.text, ts.isStringLiteralLike(value) ? JSON.stringify(value.text) : value.getText(sourceFile));
  }
  return properties;
}

function applyEdits(sourceText: string, edits: Edit[]): string {
  const sorted = [...edits].sort((a, b) => a.start - b.start || a.end - b.end);
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i].start < sorted[i - 1].end) throw new SchemaTransformError("overlapping schema edits (generator bug)");
  }
  let out = sourceText;
  for (const edit of sorted.reverse()) out = out.slice(0, edit.start) + edit.text + out.slice(edit.end);
  return out;
}

/** What schema.sqlite.ts exports: tables (by export name, in order) and types. */
export type SchemaExports = { tables: { exportName: string; tableName: string }[]; types: string[] };

export function readSchemaExports(sourceText: string, fileName = "schema.sqlite.ts"): SchemaExports {
  const sourceFile = parse(sourceText, fileName);
  const result: SchemaExports = { tables: [], types: [] };
  for (const statement of sourceFile.statements) {
    if (!hasExportModifier(statement)) {
      if (ts.isExportDeclaration(statement) || ts.isExportAssignment(statement)) {
        fail(sourceFile, statement, "re-exports are not supported in schema.sqlite.ts");
      }
      continue;
    }
    if (ts.isTypeAliasDeclaration(statement) || ts.isInterfaceDeclaration(statement)) {
      result.types.push(statement.name.text);
      continue;
    }
    if (!ts.isVariableStatement(statement)) {
      fail(sourceFile, statement, "schema.sqlite.ts may export only tables (sqliteTable) and types");
    }
    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || !declaration.initializer || !isCallTo(declaration.initializer, "sqliteTable")) {
        fail(sourceFile, declaration, "schema.sqlite.ts may export only tables (sqliteTable) and types");
      }
      result.tables.push({
        exportName: declaration.name.text,
        tableName: stringArgument(sourceFile, declaration.initializer, "sqliteTable"),
      });
    }
  }
  return result;
}

/** Turns schema.sqlite.ts into schema.pg.ts (without the generated-file header). */
export function transformToPg(
  sourceText: string,
  classification: IntegerClassification = PG_INTEGER_COLUMNS,
  fileName = "schema.sqlite.ts"
): string {
  const sourceFile = parse(sourceText, fileName);
  const edits: Edit[] = [];
  const used = new Set<string>();
  const classified = new Set<string>();
  const unclassified: string[] = [];
  let sqliteImport: ts.ImportDeclaration | undefined;
  const imported = new Set<string>();

  for (const statement of sourceFile.statements) {
    if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) continue;
    if (statement.moduleSpecifier.text !== "drizzle-orm/sqlite-core") continue;
    const bindings = statement.importClause?.namedBindings;
    if (statement.importClause?.isTypeOnly || statement.importClause?.name || !bindings || !ts.isNamedImports(bindings)) {
      fail(sourceFile, statement, "import drizzle-orm/sqlite-core only with named value imports");
    }
    if (sqliteImport) fail(sourceFile, statement, "import drizzle-orm/sqlite-core once");
    for (const element of bindings.elements) {
      const name = (element.propertyName ?? element.name).text;
      if (element.isTypeOnly || element.propertyName || !SUPPORTED_SQLITE_IMPORTS.has(name)) {
        fail(sourceFile, element, `"${name}" from drizzle-orm/sqlite-core has no PostgreSQL translation in scripts/db/generate-pg-schema.ts`);
      }
      imported.add(name);
    }
    sqliteImport = statement;
  }

  const integerType = (node: ts.Node, table: string, column: string): PgIntegerType => {
    const width = Object.hasOwn(classification, table) && Object.hasOwn(classification[table], column)
      ? classification[table][column]
      : undefined;
    classified.add(`${table}.${column}`);
    if (!width) {
      unclassified.push(`${position(sourceFile, node)}: ${table}.${column}`);
      return "int4";
    }
    return width;
  };

  /** The column builder call a method chain starts from (integer("id") in integer("id").primaryKey()). */
  const chainRoot = (node: ts.Expression): ts.Expression => {
    let current = node;
    while (ts.isCallExpression(current) && ts.isPropertyAccessExpression(current.expression)) {
      current = current.expression.expression;
    }
    return current;
  };

  const isBooleanInteger = (call: ts.CallExpression): boolean => {
    const config = call.arguments[1];
    return !!config && objectProperties(sourceFile, config).get("mode") === '"boolean"';
  };

  const visitInteger = (call: ts.CallExpression, table: string | undefined) => {
    if (!table) fail(sourceFile, call, "integer() outside a sqliteTable() call cannot be classified");
    const column = stringArgument(sourceFile, call, "integer()");
    const name = call.arguments[0].getText(sourceFile);
    if (call.arguments.length > 2) fail(sourceFile, call, "unexpected integer() arguments");
    const config = call.arguments[1] ? objectProperties(sourceFile, call.arguments[1]) : new Map<string, string>();
    for (const key of config.keys()) {
      if (key !== "mode") fail(sourceFile, call, `integer() option "${key}" has no PostgreSQL translation`);
    }
    const mode = config.get("mode");
    let replacement: string;
    if (mode === '"boolean"') {
      used.add("boolean");
      replacement = `boolean(${name})`;
    } else if (mode === undefined || mode === '"number"') {
      if (integerType(call, table, column) === "int8") {
        used.add("bigint");
        replacement = `bigint(${name}, { mode: "number" })`;
      } else {
        used.add("integer");
        replacement = `integer(${name})`;
      }
    } else {
      fail(sourceFile, call, `integer() mode ${mode} has no PostgreSQL translation`);
    }
    if (replacement !== call.getText(sourceFile)) {
      edits.push({ start: call.getStart(sourceFile), end: call.end, text: replacement });
    }
  };

  const visitText = (call: ts.CallExpression, table: string | undefined) => {
    if (!table) fail(sourceFile, call, "text() outside a sqliteTable() call");
    stringArgument(sourceFile, call, "text()");
    used.add("text");
    if (call.arguments.length > 2) fail(sourceFile, call, "unexpected text() arguments");
    if (!call.arguments[1]) return;
    // SQLite ignores a declared length; so does a PostgreSQL text column.
    for (const key of objectProperties(sourceFile, call.arguments[1]).keys()) {
      if (key !== "length") fail(sourceFile, call, `text() option "${key}" has no PostgreSQL translation`);
    }
    edits.push({ start: call.getStart(sourceFile), end: call.end, text: `text(${call.arguments[0].getText(sourceFile)})` });
  };

  const visitSql = (template: ts.TemplateLiteral) => {
    const pieces = ts.isNoSubstitutionTemplateLiteral(template)
      ? [template]
      : [template.head, ...template.templateSpans.map((span) => span.literal)];
    for (const piece of pieces) {
      const text = piece.getText(sourceFile);
      const untranslated = UNTRANSLATED_SQL.exec(text);
      if (untranslated) fail(sourceFile, piece, `sql\`\` uses ${untranslated[1]}, which has no PostgreSQL translation here`);
      const translated = text.replace(/\bifnull(\s*\()/gi, "coalesce$1");
      if (translated !== text) edits.push({ start: piece.getStart(sourceFile), end: piece.end, text: translated });
    }
  };

  const visit = (node: ts.Node, table: string | undefined): void => {
    if (ts.isImportDeclaration(node)) return;
    if (ts.isCallExpression(node)) {
      const callee = node.expression;
      if (ts.isIdentifier(callee)) {
        if (callee.text === "sqliteTable") {
          if (table) fail(sourceFile, node, "nested sqliteTable()");
          const tableName = stringArgument(sourceFile, node, "sqliteTable()");
          const [, columns, extra, ...rest] = node.arguments;
          if (!columns || !ts.isObjectLiteralExpression(columns) || rest.length > 0) {
            fail(sourceFile, node, "sqliteTable() needs a name, a columns object and optionally an extra config");
          }
          used.add("pgTable");
          edits.push({ start: callee.getStart(sourceFile), end: callee.end, text: "pgTable" });
          visit(columns, tableName);
          if (extra) visit(extra, tableName);
          return;
        }
        if (callee.text === "integer") return visitInteger(node, table);
        if (callee.text === "text") return visitText(node, table);
        if (callee.text === "index" || callee.text === "uniqueIndex") used.add(callee.text);
      } else if (ts.isPropertyAccessExpression(callee)) {
        const method = callee.name.text;
        if (method === "references") {
          // Not enforced on SQLite (foreign_keys is off), so not declared on PostgreSQL.
          edits.push({ start: callee.expression.end, end: node.end, text: "" });
          return visit(callee.expression, table);
        }
        if (method === "primaryKey" && node.arguments.length > 0) {
          const root = chainRoot(callee.expression);
          const config = node.arguments.length === 1 ? objectProperties(sourceFile, node.arguments[0]) : undefined;
          if (!config || config.size !== 1 || config.get("autoIncrement") !== "true") {
            fail(sourceFile, node, "only primaryKey() and primaryKey({ autoIncrement: true }) are supported");
          }
          if (!isCallTo(root, "integer") || isBooleanInteger(root)) {
            fail(sourceFile, node, "autoIncrement needs an integer() column");
          }
          edits.push({ start: callee.name.end, end: node.end, text: "().generatedByDefaultAsIdentity()" });
          return visit(callee.expression, table);
        }
      }
    }
    if (ts.isTaggedTemplateExpression(node) && ts.isIdentifier(node.tag) && node.tag.text === "sql") {
      visitSql(node.template);
    }
    ts.forEachChild(node, (child) => visit(child, table));
  };

  visit(sourceFile, undefined);

  if (unclassified.length > 0) {
    throw new SchemaTransformError(
      `integer columns missing from src/lib/db/pg-column-types.ts (classify each as "int4" or "int8"):\n  ${unclassified.join("\n  ")}`
    );
  }
  const stale = Object.entries(classification).flatMap(([table, columns]) =>
    Object.keys(columns).filter((column) => !classified.has(`${table}.${column}`)).map((column) => `${table}.${column}`)
  );
  if (stale.length > 0) {
    throw new SchemaTransformError(
      `src/lib/db/pg-column-types.ts classifies columns that are not integer columns of schema.sqlite.ts:\n  ${stale.join("\n  ")}`
    );
  }

  if (sqliteImport) {
    const names = [...used].filter((name) => (name !== "index" && name !== "uniqueIndex") || imported.has(name)).sort();
    edits.push({
      start: sqliteImport.getStart(sourceFile),
      end: sqliteImport.end,
      text: `import { ${names.join(", ")} } from "drizzle-orm/pg-core";`,
    });
  } else if (used.size > 0) {
    throw new SchemaTransformError(`${fileName}: column builders used without importing drizzle-orm/sqlite-core`);
  }

  return applyEdits(sourceText, edits);
}

/**
 * Whether the generated schema.ts picks the SQLite or the PostgreSQL tables
 * at module load, by getDialect() from ./dialect (on since PostgreSQL runs;
 * off renders the SQLite-only switch).
 */
export const SWITCH_WITH_POSTGRES = true;

/** The generated schema.ts: every table, typed as its SQLite table. */
export function renderSwitch(schema: SchemaExports, { withPostgres = SWITCH_WITH_POSTGRES } = {}): string {
  const lines = [
    GENERATED_NOTICE,
    "// Change schema.sqlite.ts and run `bun run db:generate-pg-schema`.",
    "/**",
    " * The tables the application queries (`@/src/lib/db/schema`). They are",
    " * authored in schema.sqlite.ts; schema.pg.ts holds the same tables for",
    " * PostgreSQL. Every table is exported typed as its SQLite table, so a query",
    " * type-checks the same way on either dialect.",
    ...(withPostgres
      ? [
          " * The dialect's tables are chosen once, at module load.",
          " */",
          'import { getDialect } from "./dialect";',
          'import * as pgSchema from "./schema.pg";',
          'import * as sqliteSchema from "./schema.sqlite";',
          "",
          'const tables = (getDialect() === "postgres" ? pgSchema : sqliteSchema) as unknown as typeof sqliteSchema;',
        ]
      : [
          " * Only SQLite runs for now, so every export is the SQLite table; the",
          " * PostgreSQL runtime will choose the dialect's tables here, at module load.",
          " */",
          'import * as sqliteSchema from "./schema.sqlite";',
          "",
          "const tables: typeof sqliteSchema = sqliteSchema;",
        ]),
    "",
    ...schema.tables.map(({ exportName }) => `export const ${exportName} = tables.${exportName};`),
  ];
  if (schema.types.length > 0) {
    lines.push("", `export type { ${schema.types.join(", ")} } from "./schema.sqlite";`);
  }
  return `${lines.join("\n")}\n`;
}

/** The generated schema.pg.ts. */
export function renderPg(sourceText: string, classification: IntegerClassification = PG_INTEGER_COLUMNS): string {
  const header = [
    GENERATED_NOTICE,
    "// Change schema.sqlite.ts (integer widths: pg-column-types.ts) and run",
    "// `bun run db:generate-pg-schema`.",
    "",
  ].join("\n");
  return `${header}${transformToPg(sourceText, classification)}`;
}

/** Both generated files, from schema.sqlite.ts under `root`. */
export function generateSchemaFiles(root = REPO_ROOT): GeneratedFile[] {
  const sourceText = readFileSync(resolve(root, SOURCE_PATH), "utf8");
  return [
    { path: SWITCH_PATH, content: renderSwitch(readSchemaExports(sourceText)) },
    { path: PG_PATH, content: renderPg(sourceText) },
  ];
}

/** The generated files whose committed content differs from what the generator emits. */
export function staleSchemaFiles(root = REPO_ROOT): string[] {
  return generateSchemaFiles(root)
    .filter(({ path, content }) => {
      const absolute = resolve(root, path);
      return !existsSync(absolute) || readFileSync(absolute, "utf8") !== content;
    })
    .map(({ path }) => path);
}

function main(args: string[]): number {
  const unknown = args.filter((arg) => arg !== "--check");
  if (unknown.length > 0) {
    console.error(`Unknown arguments: ${unknown.join(" ")}\nUsage: generate-pg-schema.ts [--check]`);
    return 2;
  }
  try {
    if (args.includes("--check")) {
      const stale = staleSchemaFiles();
      if (stale.length > 0) {
        console.error(`Stale generated schema: ${stale.join(", ")}. Run \`bun run db:generate-pg-schema\`.`);
        return 1;
      }
      console.log(`${SWITCH_PATH} and ${PG_PATH} are up to date.`);
      return 0;
    }
    for (const { path, content } of generateSchemaFiles()) {
      const absolute = resolve(REPO_ROOT, path);
      if (existsSync(absolute) && readFileSync(absolute, "utf8") === content) continue;
      writeFileSync(absolute, content);
      console.log(`Wrote ${path}`);
    }
    return 0;
  } catch (error) {
    if (!(error instanceof SchemaTransformError)) throw error;
    console.error(error.message);
    return 1;
  }
}

if (import.meta.main) process.exit(main(process.argv.slice(2)));
