-- Governance and operations.
--
-- Alerting (ee): rules gain an explicit scope (every host, or chosen proxy
-- hosts) and a "for" duration (the condition must hold that long before the
-- rule fires); a subject waiting out that duration is "pending" since
-- pendingSince.
ALTER TABLE `alert_rules` ADD `scope` text DEFAULT '{"type":"all"}' NOT NULL;
--> statement-breakpoint
ALTER TABLE `alert_rules` ADD `forMinutes` integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE `alert_rule_states` ADD `pendingSince` text;
--> statement-breakpoint
-- Audit log: the configuration history versions (config_snapshots ids) taken
-- before and after a configuration change, and the change request that
-- applied it. Not covered by the hash chain, like organizationId; events
-- recorded before this migration have none.
ALTER TABLE `audit_events` ADD `configBeforeId` integer;
--> statement-breakpoint
ALTER TABLE `audit_events` ADD `configAfterId` integer;
--> statement-breakpoint
ALTER TABLE `audit_events` ADD `changeRequestId` integer;
--> statement-breakpoint
CREATE INDEX `audit_events_config_after_idx` ON `audit_events` (`configAfterId`);
--> statement-breakpoint
CREATE INDEX `audit_events_user_idx` ON `audit_events` (`userId`, `createdAt`);
--> statement-breakpoint
CREATE INDEX `audit_events_entity_idx` ON `audit_events` (`entityType`, `entityId`);
--> statement-breakpoint
-- Configuration history: what changed from the previous version (computed
-- once, when the version is recorded or first listed).
ALTER TABLE `config_snapshots` ADD `previousId` integer;
--> statement-breakpoint
ALTER TABLE `config_snapshots` ADD `changes` text;
--> statement-breakpoint
-- Compliance (ee): reports generated by a schedule, grouped per run.
ALTER TABLE `compliance_reports` ADD `scheduleId` integer;
--> statement-breakpoint
ALTER TABLE `compliance_reports` ADD `packId` text;
--> statement-breakpoint
CREATE INDEX `compliance_reports_pack_idx` ON `compliance_reports` (`packId`);
--> statement-breakpoint
-- Compliance (ee): the incident register. Existing notification drafts keep
-- every value and start "undetermined".
ALTER TABLE `compliance_incidents` ADD `startedAt` text;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `endedAt` text;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `classification` text DEFAULT 'undetermined' NOT NULL;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `classifiedAt` text;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `classifiedBy` integer;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `classifiedByName` text;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `assessment` text DEFAULT '{}' NOT NULL;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `cause` text;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `timeline` text DEFAULT '[]' NOT NULL;
--> statement-breakpoint
ALTER TABLE `compliance_incidents` ADD `closedAt` text;
--> statement-breakpoint
CREATE TABLE `compliance_report_schedules` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`enabled` integer DEFAULT true NOT NULL,
	`frequency` text NOT NULL,
	`weekday` text,
	`dayOfMonth` integer,
	`time` text DEFAULT '06:00' NOT NULL,
	`timeZone` text DEFAULT 'UTC' NOT NULL,
	`reportTypes` text DEFAULT '["access_review","change_log","certificate_inventory","protection_coverage"]' NOT NULL,
	`channelIds` text DEFAULT '[]' NOT NULL,
	`nextRunAt` text,
	`lastRunAt` text,
	`lastStatus` text,
	`lastError` text,
	`lastPackId` text,
	`lastDeliveries` text,
	`createdBy` integer,
	`createdAt` text NOT NULL,
	`updatedAt` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `compliance_restore_tests` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`testedAt` text NOT NULL,
	`source` text NOT NULL,
	`backupDestinationId` integer,
	`backupObjectKey` text,
	`outcome` text NOT NULL,
	`notes` text,
	`recordedBy` integer,
	`recordedByName` text,
	`createdAt` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `compliance_restore_tests_tested_at_idx` ON `compliance_restore_tests` (`testedAt`);
