// SPDX-License-Identifier: Elastic-2.0
import { requirePermission } from "@/src/lib/auth";
import { can } from "@/src/lib/permissions";
import { EDITION_LABELS, FEATURE_INFO } from "@/ee/licensing/features";
import { isFeatureConfigurable } from "@/ee/licensing/store";
import { describeControlMapping } from "@/ee/compliance/controls";
import { getControlStatus } from "@/ee/compliance/control-status";
import { getReport, listReports } from "@/ee/compliance/reports";
import { listEvidencePacks, listReportSchedules } from "@/ee/compliance/schedules";
import { listRestoreTests } from "@/ee/compliance/restore-tests";
import { listDraftSources, listIncidents } from "@/ee/compliance/incidents";
import { FEATURE, readComplianceFramework, readComplianceTab, type StoredReportSummary } from "@/ee/compliance/types";
import { listAlertChannels } from "@/ee/alerting/channels";
import { listSavedQuestions } from "@/ee/ai/questions/saved";
import { getQuestionAvailability } from "@/ee/ai/questions/availability";
import { listBackupDestinations } from "@/ee/backups/destinations";
import ComplianceClient from "@/ee/compliance/ui/ComplianceClient";
import type { LastReportView, ShownReport } from "@/ee/compliance/ui/LastReportCard";

export const metadata = { title: "Compliance" };

const REPORTS_PER_PAGE = 25;

/** A report with whether it still matches its SHA-256 and the hash its audit event recorded. */
async function withIntegrity(report: StoredReportSummary): Promise<ShownReport> {
  try {
    const { integrity } = await getReport(report.id);
    if (!integrity.contentMatches) return { ...report, integrity: { tone: "bad", text: "Changed since it was generated" } };
    if (!integrity.auditEvent) return { ...report, integrity: { tone: "warn", text: "Intact; its audit event is no longer kept" } };
    if (!integrity.auditEvent.sha256Matches) return { ...report, integrity: { tone: "bad", text: "Differs from the SHA-256 in its audit event" } };
    return { ...report, integrity: { tone: "ok", text: "Intact, matches its audit event" } };
  } catch {
    return { ...report, integrity: { tone: "warn", text: "Could not be checked" } };
  }
}

/** The newest evidence pack, or the newest report when one was generated by hand after it. */
async function lastReport(): Promise<LastReportView | null> {
  const [[pack], { reports: [newest] }] = await Promise.all([listEvidencePacks(1), listReports({ page: 1, perPage: 1 })]);
  if (pack && pack.reports.length > 0 && (!newest || newest.packId === pack.packId || pack.generatedAt >= newest.generatedAt)) {
    return { kind: "pack", scheduleId: pack.scheduleId, generatedAt: pack.generatedAt, reports: await Promise.all(pack.reports.map(withIntegrity)) };
  }
  if (!newest) return null;
  return { kind: "report", scheduleId: newest.scheduleId, generatedAt: newest.generatedAt, reports: [await withIntegrity(newest)] };
}

export default async function CompliancePage({
  searchParams,
}: {
  searchParams: Promise<{ tab?: string; page?: string; framework?: string; incident?: string }>;
}) {
  const { access } = await requirePermission("compliance:read");
  const { tab: tabParam, page: pageParam, framework, incident } = await searchParams;
  const page = Math.max(1, Number.parseInt(pageParam ?? "1", 10) || 1);
  const canWrite = can(access, "compliance:write");
  // Reports are listed without their content; draft sources are ids, names and titles only;
  // of alert channels and backup destinations only ids, names and types reach the page.
  const canAsk = can(access, "analytics:read");
  const [reports, incidents, controls, schedules, restoreTests, last, configurable, channels, destinations, savedQuestions, askAvailability] = await Promise.all([
    listReports({ page, perPage: REPORTS_PER_PAGE }),
    listIncidents({ page: 1, perPage: 100 }),
    getControlStatus(),
    listReportSchedules(),
    listRestoreTests({ page: 1, perPage: 20 }),
    lastReport(),
    isFeatureConfigurable(FEATURE),
    canWrite ? listAlertChannels() : Promise.resolve([]),
    canWrite && can(access, "backups:read") ? listBackupDestinations() : Promise.resolve([]),
    // Saved analytics questions a schedule can include: the user's own and the shared ones they can see.
    canWrite ? listSavedQuestions(access) : Promise.resolve([]),
    canAsk ? getQuestionAvailability() : Promise.resolve(null),
  ]);
  const openIncident = Number.parseInt(incident ?? "", 10);
  return (
    <ComplianceClient
      initialTab={readComplianceTab(tabParam)}
      initialFramework={readComplianceFramework(framework)}
      initialIncidentId={Number.isSafeInteger(openIncident) && openIncident > 0 ? openIncident : null}
      reports={reports}
      incidents={incidents.incidents}
      controls={controls}
      schedules={schedules}
      restoreTests={restoreTests}
      lastReport={last}
      channels={channels.map((channel) => ({ id: channel.id, name: channel.name, type: channel.type }))}
      destinations={destinations.map((destination) => ({ id: destination.id, name: destination.name }))}
      sources={canWrite ? await listDraftSources() : { alertEvents: [], proxyHosts: [] }}
      mapping={describeControlMapping()}
      configurable={configurable}
      canWrite={canWrite}
      editionLabel={EDITION_LABELS[FEATURE_INFO[FEATURE].edition]}
      questions={savedQuestions.map((question) => ({ id: question.id, question: question.question, interpretation: question.interpretation }))}
      ask={askAvailability ? { availability: askAvailability, isAdmin: access.isAdmin, canOpenAiSettings: can(access, "ai:read") } : null}
    />
  );
}
