// SPDX-License-Identifier: Elastic-2.0
/**
 * Renders a compliance report document: on the report page in the dashboard
 * and on the print view. No client hooks; colours are theme tokens, which the
 * print view pins to the light theme, so it stays black on white.
 */
import type { ComplianceReportDocument, FindingSeverity, ReportCell, ReportSection } from "../types";

const SEVERITY_CLASSES: Record<FindingSeverity, string> = {
  high: "bg-bad-tint text-bad border-line2",
  medium: "bg-warn-tint text-warn border-line2",
  low: "bg-brand-tint text-brand border-line2",
  info: "bg-raise text-muted-foreground border-line2",
};

export function SeverityPill({ severity }: { severity: FindingSeverity }) {
  return (
    <span className={`inline-block rounded border px-1.5 py-0.5 text-[11px] font-semibold uppercase leading-none ${SEVERITY_CLASSES[severity]}`}>
      {severity}
    </span>
  );
}

export function formatCell(value: ReportCell): string {
  if (value === null || value === undefined) return "—";
  if (Array.isArray(value)) return value.length ? value.join(", ") : "—";
  if (typeof value === "boolean") return value ? "yes" : "no";
  return String(value);
}

function formatTime(iso: string): string {
  return `${iso.slice(0, 10)} ${iso.slice(11, 19)} UTC`;
}

function SectionTable({ section }: { section: ReportSection }) {
  return (
    <section className="space-y-2 break-inside-avoid-page">
      <h2 className="text-base font-semibold">{section.title}</h2>
      {section.description && <p className="text-xs text-muted-foreground">{section.description}</p>}
      {section.rows.length === 0 ? (
        <p className="text-xs text-muted-foreground">None.</p>
      ) : (
        <div className="overflow-x-auto print:overflow-visible">
          <table className="w-full border-collapse text-xs print:text-[9px]">
            <thead>
              <tr>
                {section.columns.map((column) => (
                  <th key={column.key} className="border border-border bg-muted/50 px-2 py-1 text-left align-bottom font-semibold">
                    {column.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {section.rows.map((row, index) => (
                <tr key={index} className="break-inside-avoid">
                  {section.columns.map((column) => (
                    <td key={column.key} className="border border-border px-2 py-1 align-top break-words [overflow-wrap:anywhere]">
                      {formatCell(row[column.key] ?? null)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      {section.truncated && (
        <p className="text-xs text-muted-foreground">
          Shows the first {section.truncated.shown} of {section.truncated.total} rows.
        </p>
      )}
    </section>
  );
}

export default function ReportDocumentView({ document, sha256 }: { document: ComplianceReportDocument; sha256: string }) {
  const generator = [document.generatedBy.name, document.generatedBy.email ? `<${document.generatedBy.email}>` : null].filter(Boolean).join(" ");
  return (
    <article className="space-y-6 text-sm text-foreground">
      <header className="space-y-2 border-b border-border pb-4">
        <p className="text-xs uppercase tracking-wide text-muted-foreground">
          {document.product.name} compliance report
        </p>
        <h1 className="text-2xl font-bold tracking-tight">{document.title}</h1>
        <dl className="grid grid-cols-1 gap-x-6 gap-y-1 text-xs sm:grid-cols-2">
          <div className="flex gap-2">
            <dt className="text-muted-foreground">Period</dt>
            <dd>{formatTime(document.period.from)} to {formatTime(document.period.to)}</dd>
          </div>
          <div className="flex gap-2">
            <dt className="text-muted-foreground">Generated</dt>
            <dd>{formatTime(document.generatedAt)}</dd>
          </div>
          <div className="flex gap-2">
            <dt className="text-muted-foreground">Generated by</dt>
            <dd>
              {document.generatedBy.userId === null
                ? generator || "A report schedule"
                : `${generator || `user ${document.generatedBy.userId}`} (id ${document.generatedBy.userId})`}
            </dd>
          </div>
          <div className="flex gap-2">
            <dt className="text-muted-foreground">Product</dt>
            <dd>
              {document.product.name} {document.product.version} ({document.instanceMode})
            </dd>
          </div>
          <div className="flex gap-2">
            <dt className="text-muted-foreground">Report id</dt>
            <dd className="font-mono">{document.reportId}</dd>
          </div>
          <div className="flex gap-2 sm:col-span-2">
            <dt className="text-muted-foreground shrink-0">SHA-256</dt>
            <dd className="font-mono break-all">{sha256}</dd>
          </div>
        </dl>
      </header>

      <p className="rounded-md border border-border bg-muted/40 p-3 text-xs">{document.statement}</p>

      <section className="space-y-2 break-inside-avoid-page">
        <h2 className="text-base font-semibold">Controls this report supports</h2>
        <table className="w-full border-collapse text-xs">
          <thead>
            <tr>
              <th className="border border-border bg-muted/50 px-2 py-1 text-left font-semibold">Framework</th>
              <th className="border border-border bg-muted/50 px-2 py-1 text-left font-semibold">Control</th>
              <th className="border border-border bg-muted/50 px-2 py-1 text-left font-semibold">How the report supports it</th>
            </tr>
          </thead>
          <tbody>
            {document.controls.map((control) => (
              <tr key={`${control.framework}-${control.ref}`} className="break-inside-avoid">
                <td className="border border-border px-2 py-1 align-top whitespace-nowrap">{control.framework}</td>
                <td className="border border-border px-2 py-1 align-top">
                  <span className="font-medium">{control.ref}</span> {control.title}
                </td>
                <td className="border border-border px-2 py-1 align-top">{control.how}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="space-y-2 break-inside-avoid-page">
        <h2 className="text-base font-semibold">Summary</h2>
        <dl className="grid grid-cols-1 gap-x-6 gap-y-1 text-xs sm:grid-cols-2">
          {document.summary.map((item) => (
            <div key={item.key} className="flex justify-between gap-4 border-b border-border/60 py-1">
              <dt className="text-muted-foreground">{item.label}</dt>
              <dd className="font-medium text-right">{formatCell(item.value)}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold">Findings ({document.findings.length})</h2>
        {document.findings.length === 0 ? (
          <p className="text-xs text-muted-foreground">No findings.</p>
        ) : (
          <table className="w-full border-collapse text-xs">
            <thead>
              <tr>
                <th className="border border-border bg-muted/50 px-2 py-1 text-left font-semibold">Severity</th>
                <th className="border border-border bg-muted/50 px-2 py-1 text-left font-semibold">Finding</th>
                <th className="border border-border bg-muted/50 px-2 py-1 text-left font-semibold">Subject</th>
              </tr>
            </thead>
            <tbody>
              {document.findings.map((item, index) => (
                <tr key={index} className="break-inside-avoid">
                  <td className="border border-border px-2 py-1 align-top">
                    <SeverityPill severity={item.severity} />
                  </td>
                  <td className="border border-border px-2 py-1 align-top">
                    {item.message} <span className="font-mono text-[11px] text-muted-foreground">({item.code})</span>
                  </td>
                  <td className="border border-border px-2 py-1 align-top font-mono text-[11px]">{item.subject}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      {document.sections.map((section) => (
        <SectionTable key={section.key} section={section} />
      ))}

      {document.notes.length > 0 && (
        <section className="space-y-2 break-inside-avoid-page">
          <h2 className="text-base font-semibold">Notes</h2>
          <ul className="list-disc space-y-1 pl-5 text-xs text-muted-foreground">
            {document.notes.map((note, index) => (
              <li key={index}>{note}</li>
            ))}
          </ul>
        </section>
      )}
    </article>
  );
}
