-- PostgreSQL baseline: the database that the SQLite migrations in drizzle/
-- build, up to and including 0052_ha_shared_state
-- (meta/_sqlite-equivalence.json). The tables and indexes are drizzle-kit's
-- output for src/lib/db/schema.pg.ts (meta/0000_snapshot.json), unchanged;
-- what the Drizzle schema does not express follows them, at the end. No
-- foreign keys: SQLite does not enforce the ones it declares either.
CREATE TABLE "access_list_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_list_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"accessListId" integer NOT NULL,
	"username" text NOT NULL,
	"passwordHash" text NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "access_list_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_list_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"accessListId" integer NOT NULL,
	"position" integer NOT NULL,
	"action" text NOT NULL,
	"kind" text NOT NULL,
	"matchValues" text NOT NULL,
	"note" text,
	"expiresAt" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "access_lists" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_lists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL,
	"organizationId" integer,
	"defaultAction" text DEFAULT 'allow' NOT NULL,
	"denyStatus" integer DEFAULT 403 NOT NULL,
	"denyBody" text,
	"denyRedirectUrl" text,
	"failClosed" boolean DEFAULT false NOT NULL,
	"systemKey" text
);
--> statement-breakpoint
CREATE TABLE "access_review_campaigns" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_review_campaigns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"scope" text DEFAULT '{"type":"all"}' NOT NULL,
	"reviewerIds" text DEFAULT '[]' NOT NULL,
	"dueAt" text NOT NULL,
	"startedAt" text NOT NULL,
	"completedAt" text,
	"cancelledAt" text,
	"scheduleId" integer,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "access_review_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_review_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaignId" integer NOT NULL,
	"subjectUserId" integer NOT NULL,
	"subjectEmail" text NOT NULL,
	"subjectName" text,
	"kind" text NOT NULL,
	"targetId" integer,
	"targetLabel" text NOT NULL,
	"decision" text,
	"comment" text,
	"decidedBy" integer,
	"decidedByEmail" text,
	"decidedAt" text,
	"confirmedAt" text,
	"outcome" text,
	"outcomeDetail" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "access_review_schedules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_review_schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"scope" text DEFAULT '{"type":"all"}' NOT NULL,
	"reviewerIds" text DEFAULT '[]' NOT NULL,
	"durationDays" integer DEFAULT 14 NOT NULL,
	"intervalMonths" integer DEFAULT 3 NOT NULL,
	"nextRunAt" text NOT NULL,
	"lastRunAt" text,
	"lastCampaignId" integer,
	"lastError" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"issuer" text DEFAULT '' NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" text,
	"refreshTokenExpiresAt" text,
	"scope" text,
	"password" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alert_channels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_channels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"config" text DEFAULT '{}' NOT NULL,
	"secrets" text,
	"lastDeliveryAt" text,
	"lastDeliveryError" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alert_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruleId" integer NOT NULL,
	"ruleName" text NOT NULL,
	"ruleType" text NOT NULL,
	"subjectKey" text NOT NULL,
	"status" text NOT NULL,
	"severity" text NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"facts" text,
	"explanation" text,
	"notified" boolean DEFAULT false NOT NULL,
	"deliveries" text,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alert_rule_states" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_rule_states_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruleId" integer NOT NULL,
	"subjectKey" text NOT NULL,
	"status" text NOT NULL,
	"title" text,
	"firedAt" text,
	"resolvedAt" text,
	"lastNotifiedAt" text,
	"notifiedFiring" boolean DEFAULT false NOT NULL,
	"lastEvaluatedAt" text NOT NULL,
	"pendingSince" text
);
--> statement-breakpoint
CREATE TABLE "alert_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"params" text DEFAULT '{}' NOT NULL,
	"channelIds" text DEFAULT '[]' NOT NULL,
	"cooldownMinutes" integer DEFAULT 60 NOT NULL,
	"notifyOnResolve" boolean DEFAULT true NOT NULL,
	"explain" boolean DEFAULT false NOT NULL,
	"scope" text DEFAULT '{"type":"all"}' NOT NULL,
	"forMinutes" integer DEFAULT 0 NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "analytics_questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "analytics_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"organizationId" integer,
	"question" text NOT NULL,
	"query" text NOT NULL,
	"shared" boolean DEFAULT false NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "analytics_saved_views" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "analytics_saved_views_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"organizationId" integer,
	"name" text NOT NULL,
	"shared" boolean DEFAULT false NOT NULL,
	"range" text NOT NULL,
	"filters" text DEFAULT '[]' NOT NULL,
	"metric" text DEFAULT 'requests' NOT NULL,
	"groupBy" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "api_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"tokenHash" text NOT NULL,
	"createdBy" integer NOT NULL,
	"createdAt" text NOT NULL,
	"lastUsedAt" text,
	"expiresAt" text,
	"scopes" text
);
--> statement-breakpoint
CREATE TABLE "approval_policies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "approval_policies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"targetTypes" text DEFAULT '["proxy_host","l4_proxy_host"]' NOT NULL,
	"operations" text DEFAULT '["create","update","delete","enable","disable"]' NOT NULL,
	"hostTags" text DEFAULT '[]' NOT NULL,
	"requiredApprovals" integer DEFAULT 1 NOT NULL,
	"allowEmergency" boolean DEFAULT true NOT NULL,
	"timeZone" text DEFAULT 'UTC' NOT NULL,
	"windows" text DEFAULT '[]' NOT NULL,
	"requestTtlHours" integer DEFAULT 72 NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer,
	"action" text NOT NULL,
	"entityType" text NOT NULL,
	"entityId" integer,
	"summary" text,
	"data" text,
	"createdAt" text NOT NULL,
	"prevHash" text,
	"hash" text,
	"actorDigest" text,
	"organizationId" integer,
	"configBeforeId" integer,
	"configAfterId" integer,
	"changeRequestId" integer
);
--> statement-breakpoint
CREATE TABLE "audit_sinks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_sinks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"config" text NOT NULL,
	"secret" text,
	"lastDeliveredId" integer DEFAULT 0 NOT NULL,
	"lastDeliveryAt" text,
	"lastError" text,
	"lastErrorAt" text,
	"consecutiveFailures" integer DEFAULT 0 NOT NULL,
	"nextAttemptAt" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "backup_destinations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "backup_destinations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"endpoint" text NOT NULL,
	"region" text NOT NULL,
	"bucket" text NOT NULL,
	"keyPrefix" text DEFAULT '' NOT NULL,
	"pathStyle" boolean DEFAULT false NOT NULL,
	"accessKeyId" text NOT NULL,
	"secretAccessKey" text NOT NULL,
	"passphrase" text NOT NULL,
	"schedule" text NOT NULL,
	"timeZone" text DEFAULT 'UTC' NOT NULL,
	"retention" integer DEFAULT 30 NOT NULL,
	"nextRunAt" text,
	"lastRunAt" text,
	"lastStatus" text,
	"lastError" text,
	"lastSuccessAt" text,
	"consecutiveFailures" integer DEFAULT 0 NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "backup_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "backup_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"destinationId" integer NOT NULL,
	"trigger" text NOT NULL,
	"status" text NOT NULL,
	"startedAt" text NOT NULL,
	"finishedAt" text,
	"objectKey" text,
	"sizeBytes" bigint,
	"sha256" text,
	"prunedCount" integer,
	"error" text,
	"warning" text
);
--> statement-breakpoint
CREATE TABLE "ca_certificates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ca_certificates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"certificatePem" text NOT NULL,
	"privateKeyPem" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "certificates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "certificates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"domainNames" text NOT NULL,
	"autoRenew" boolean DEFAULT true NOT NULL,
	"providerOptions" text,
	"certificatePem" text,
	"privateKeyPem" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL,
	"organizationId" integer
);
--> statement-breakpoint
CREATE TABLE "change_request_reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "change_request_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"requestId" integer NOT NULL,
	"userId" integer NOT NULL,
	"decision" text NOT NULL,
	"comment" text,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "change_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"targetType" text NOT NULL,
	"targetId" integer,
	"targetName" text NOT NULL,
	"operation" text NOT NULL,
	"operations" text DEFAULT '[]' NOT NULL,
	"input" text NOT NULL,
	"baseState" text,
	"baseFingerprint" text,
	"tags" text DEFAULT '[]' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"requiredApprovals" integer DEFAULT 1 NOT NULL,
	"policyIds" text DEFAULT '[]' NOT NULL,
	"policyNames" text DEFAULT '[]' NOT NULL,
	"note" text,
	"requestedBy" integer NOT NULL,
	"emergency" boolean DEFAULT false NOT NULL,
	"emergencyReason" text,
	"emergencyBy" integer,
	"expiresAt" text NOT NULL,
	"decidedAt" text,
	"appliedAt" text,
	"appliedBy" integer,
	"error" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "compliance_incidents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "compliance_incidents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"language" text DEFAULT 'en' NOT NULL,
	"detectedAt" text NOT NULL,
	"periodFrom" text NOT NULL,
	"periodTo" text NOT NULL,
	"alertEventId" integer,
	"proxyHostIds" text DEFAULT '[]' NOT NULL,
	"facts" text,
	"factsCollectedAt" text,
	"stages" text DEFAULT '{}' NOT NULL,
	"createdBy" integer,
	"createdByName" text,
	"createdAt" text NOT NULL,
	"updatedBy" integer,
	"updatedAt" text NOT NULL,
	"startedAt" text,
	"endedAt" text,
	"classification" text DEFAULT 'undetermined' NOT NULL,
	"classifiedAt" text,
	"classifiedBy" integer,
	"classifiedByName" text,
	"assessment" text DEFAULT '{}' NOT NULL,
	"cause" text,
	"timeline" text DEFAULT '[]' NOT NULL,
	"closedAt" text
);
--> statement-breakpoint
CREATE TABLE "compliance_report_schedules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "compliance_report_schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"frequency" text NOT NULL,
	"weekday" text,
	"dayOfMonth" integer,
	"time" text DEFAULT '06:00' NOT NULL,
	"timeZone" text DEFAULT 'UTC' NOT NULL,
	"reportTypes" text DEFAULT '["access_review","change_log","certificate_inventory","protection_coverage"]' NOT NULL,
	"channelIds" text DEFAULT '[]' NOT NULL,
	"nextRunAt" text,
	"lastRunAt" text,
	"lastStatus" text,
	"lastError" text,
	"lastPackId" text,
	"lastDeliveries" text,
	"questions" text DEFAULT '[]' NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "compliance_reports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "compliance_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" text NOT NULL,
	"type" text NOT NULL,
	"periodFrom" text NOT NULL,
	"periodTo" text NOT NULL,
	"generatedAt" text NOT NULL,
	"generatedBy" integer,
	"generatedByName" text,
	"sha256" text NOT NULL,
	"findingCounts" text DEFAULT '{}' NOT NULL,
	"sizeBytes" bigint NOT NULL,
	"content" text NOT NULL,
	"scheduleId" integer,
	"packId" text
);
--> statement-breakpoint
CREATE TABLE "compliance_restore_tests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "compliance_restore_tests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"testedAt" text NOT NULL,
	"source" text NOT NULL,
	"backupDestinationId" integer,
	"backupObjectKey" text,
	"outcome" text NOT NULL,
	"notes" text,
	"recordedBy" integer,
	"recordedByName" text,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "config_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "config_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdAt" text NOT NULL,
	"userId" integer,
	"reason" text NOT NULL,
	"summary" text NOT NULL,
	"fingerprint" text NOT NULL,
	"content" text NOT NULL,
	"sizeBytes" bigint NOT NULL,
	"previousId" integer,
	"changes" text
);
--> statement-breakpoint
CREATE TABLE "custom_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"permissions" text DEFAULT '[]' NOT NULL,
	"scopeTags" text DEFAULT '[]' NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_environments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_environments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"position" integer NOT NULL,
	"promotionOnly" boolean DEFAULT false NOT NULL,
	"revisionId" integer,
	"canaryEnabled" boolean DEFAULT true NOT NULL,
	"canaryWaitSeconds" integer DEFAULT 300 NOT NULL,
	"checkCaddyStatus" boolean DEFAULT true NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_instances" (
	"instanceId" integer PRIMARY KEY NOT NULL,
	"environmentId" integer,
	"revisionId" integer,
	"pushedFingerprint" text,
	"pushedAt" text,
	"driftStatus" text,
	"driftCheckedAt" text,
	"driftSince" text,
	"driftDetail" text,
	"reportedFingerprint" text,
	"reportedVersion" text,
	"localChanges" boolean,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_pull_replicas" (
	"instanceId" integer PRIMARY KEY NOT NULL,
	"credentialHash" text,
	"credentialPrefix" text,
	"credentialCreatedAt" text,
	"fingerprintToken" text,
	"pollIntervalSeconds" integer,
	"lastSeenAt" text,
	"lastSeenAddress" text,
	"lastStatus" text,
	"deliveredFingerprint" text,
	"deliveredRevisionId" integer,
	"deliveredAt" text,
	"resyncRequestedAt" text,
	"resyncRevisionId" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_revisions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_revisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdAt" text NOT NULL,
	"createdBy" integer,
	"summary" text NOT NULL,
	"fingerprint" text NOT NULL,
	"content" text NOT NULL,
	"sizeBytes" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_rollout_targets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_rollout_targets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rolloutId" integer NOT NULL,
	"instanceId" integer NOT NULL,
	"instanceName" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"error" text,
	"syncedAt" text,
	"requestedAt" text
);
--> statement-breakpoint
CREATE TABLE "fleet_rollouts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fleet_rollouts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"environmentId" integer NOT NULL,
	"revisionId" integer NOT NULL,
	"fromRevisionId" integer,
	"kind" text NOT NULL,
	"sourceEnvironmentId" integer,
	"rollbackOfId" integer,
	"status" text NOT NULL,
	"phase" text NOT NULL,
	"canaryInstanceId" integer,
	"canaryWaitSeconds" integer DEFAULT 0 NOT NULL,
	"checkCaddyStatus" boolean DEFAULT false NOT NULL,
	"observeUntil" text,
	"lastCheckAt" text,
	"error" text,
	"startedBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL,
	"finishedAt" text
);
--> statement-breakpoint
CREATE TABLE "forward_auth_access" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forward_auth_access_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proxyHostId" integer NOT NULL,
	"userId" integer,
	"groupId" integer,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forward_auth_exchanges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forward_auth_exchanges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"proxyHostId" integer NOT NULL,
	"audienceOrigin" text NOT NULL,
	"codeHash" text NOT NULL,
	"sessionToken" text NOT NULL,
	"redirectUri" text NOT NULL,
	"expiresAt" text NOT NULL,
	"used" boolean DEFAULT false NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forward_auth_redirect_intents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forward_auth_redirect_intents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ridHash" text NOT NULL,
	"proxyHostId" integer NOT NULL,
	"audienceOrigin" text NOT NULL,
	"redirectUri" text NOT NULL,
	"expiresAt" text NOT NULL,
	"consumed" boolean DEFAULT false NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forward_auth_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forward_auth_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"proxyHostId" integer NOT NULL,
	"audienceOrigin" text NOT NULL,
	"tokenHash" text NOT NULL,
	"expiresAt" text NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "group_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"userId" integer NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL,
	"organizationId" integer
);
--> statement-breakpoint
CREATE TABLE "instances" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "instances_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"baseUrl" text NOT NULL,
	"apiToken" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"lastSyncAt" text,
	"lastSyncError" text,
	"syncMode" text DEFAULT 'push' NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "issued_client_certificates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issued_client_certificates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"caCertificateId" integer NOT NULL,
	"commonName" text NOT NULL,
	"serialNumber" text NOT NULL,
	"fingerprintSha256" text NOT NULL,
	"certificatePem" text NOT NULL,
	"validFrom" text NOT NULL,
	"validTo" text NOT NULL,
	"revokedAt" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "l4_proxy_hosts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "l4_proxy_hosts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"protocol" text NOT NULL,
	"listenAddress" text NOT NULL,
	"upstreams" text NOT NULL,
	"matcherType" text DEFAULT 'none' NOT NULL,
	"matcherValue" text,
	"tlsTermination" boolean DEFAULT false NOT NULL,
	"proxyProtocolVersion" text,
	"proxyProtocolReceive" boolean DEFAULT false NOT NULL,
	"ownerUserId" integer,
	"meta" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL,
	"tags" text DEFAULT '[]' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ldap_directories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ldap_directories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"url" text NOT NULL,
	"startTls" boolean DEFAULT false NOT NULL,
	"allowUnencrypted" boolean DEFAULT false NOT NULL,
	"caCertificate" text,
	"connectTimeoutMs" integer DEFAULT 5000 NOT NULL,
	"operationTimeoutMs" integer DEFAULT 10000 NOT NULL,
	"bindDn" text NOT NULL,
	"bindPassword" text NOT NULL,
	"userSearchBase" text NOT NULL,
	"userSearchFilter" text NOT NULL,
	"usernameAttribute" text DEFAULT 'uid' NOT NULL,
	"emailAttribute" text DEFAULT 'mail' NOT NULL,
	"displayNameAttribute" text DEFAULT 'cn' NOT NULL,
	"uniqueIdAttribute" text DEFAULT 'entryUUID' NOT NULL,
	"groupMode" text DEFAULT 'none' NOT NULL,
	"groupMembershipAttribute" text DEFAULT 'memberOf' NOT NULL,
	"groupSearchBase" text,
	"groupSearchFilter" text,
	"nestedGroups" boolean DEFAULT false NOT NULL,
	"groupRoleMappings" text DEFAULT '[]' NOT NULL,
	"defaultRole" text DEFAULT 'user' NOT NULL,
	"requiredGroup" text,
	"provisionUsers" boolean DEFAULT false NOT NULL,
	"linkExistingAccounts" boolean DEFAULT false NOT NULL,
	"allowWhenSsoEnforced" boolean DEFAULT false NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ldap_directory_health" (
	"directoryId" integer PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"checkedAt" text NOT NULL,
	"lastSuccessAt" text,
	"lastFailureAt" text,
	"failingSince" text,
	"lastError" text,
	"consecutiveFailures" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "linking_tokens" (
	"id" text PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"createdAt" text NOT NULL,
	"expiresAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "log_parse_state" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_consumers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monetization_consumers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" text,
	"status" text DEFAULT 'active' NOT NULL,
	"planId" integer,
	"balanceMicros" bigint DEFAULT 0 NOT NULL,
	"overdraftAllowanceMicros" bigint DEFAULT 0 NOT NULL,
	"freeUsageMonth" text,
	"freeUsageCount" integer DEFAULT 0 NOT NULL,
	"portalTokenHash" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_hosts" (
	"proxyHostId" integer PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"keyHeader" text DEFAULT 'Authorization' NOT NULL,
	"allowedPlanIds" text DEFAULT '[]' NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_keys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monetization_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"consumerId" integer NOT NULL,
	"name" text,
	"prefix" text NOT NULL,
	"keyHash" text NOT NULL,
	"createdAt" text NOT NULL,
	"lastUsedAt" text,
	"revokedAt" text
);
--> statement-breakpoint
CREATE TABLE "monetization_ledger" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monetization_ledger_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"consumerId" integer NOT NULL,
	"type" text NOT NULL,
	"amountMicros" bigint NOT NULL,
	"balanceAfterMicros" bigint NOT NULL,
	"requests" bigint DEFAULT 0 NOT NULL,
	"freeRequests" bigint DEFAULT 0 NOT NULL,
	"externalReference" text,
	"description" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_plans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monetization_plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"pricePerRequestMicros" bigint DEFAULT 0 NOT NULL,
	"includedRequestsPerMonth" integer DEFAULT 0 NOT NULL,
	"requestsPerMinute" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_shared_credits" (
	"creditId" text PRIMARY KEY NOT NULL,
	"consumerId" integer NOT NULL,
	"ledgerId" integer,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_shared_cursors" (
	"consumerId" integer PRIMARY KEY NOT NULL,
	"epoch" text NOT NULL,
	"chargedMicros" bigint DEFAULT 0 NOT NULL,
	"requests" bigint DEFAULT 0 NOT NULL,
	"freeRequests" bigint DEFAULT 0 NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mtls_access_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mtls_access_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proxyHostId" integer NOT NULL,
	"pathPattern" text NOT NULL,
	"allowedRoleIds" text DEFAULT '[]' NOT NULL,
	"allowedCertIds" text DEFAULT '[]' NOT NULL,
	"denyAll" boolean DEFAULT false NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"description" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mtls_certificate_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mtls_certificate_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"issuedClientCertificateId" integer NOT NULL,
	"mtlsRoleId" integer NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mtls_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mtls_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oauth_providers" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"type" text DEFAULT 'oidc' NOT NULL,
	"clientId" text NOT NULL,
	"clientSecret" text NOT NULL,
	"issuer" text,
	"authorizationUrl" text,
	"tokenUrl" text,
	"userinfoUrl" text,
	"scopes" text DEFAULT 'openid email profile' NOT NULL,
	"autoLink" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"source" text DEFAULT 'ui' NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oauth_states" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_states_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"state" text NOT NULL,
	"codeVerifier" text NOT NULL,
	"redirectTo" text,
	"createdAt" text NOT NULL,
	"expiresAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"maxProxyHosts" integer,
	"maxUsers" integer,
	"allowedUpstreams" text DEFAULT '[]' NOT NULL,
	"notes" text,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "passkeys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "passkeys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"publicKey" text NOT NULL,
	"userId" integer NOT NULL,
	"credentialID" text NOT NULL,
	"counter" bigint DEFAULT 0 NOT NULL,
	"deviceType" text NOT NULL,
	"backedUp" boolean DEFAULT false NOT NULL,
	"transports" text,
	"createdAt" text,
	"aaguid" text,
	"lastUsedAt" text
);
--> statement-breakpoint
CREATE TABLE "pending_oauth_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pending_oauth_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"provider" text NOT NULL,
	"userEmail" text NOT NULL,
	"createdAt" text NOT NULL,
	"expiresAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "proxy_hosts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "proxy_hosts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"domains" text NOT NULL,
	"upstreams" text NOT NULL,
	"certificateId" integer,
	"accessListId" integer,
	"ownerUserId" integer,
	"sslForced" boolean DEFAULT true NOT NULL,
	"hstsEnabled" boolean DEFAULT true NOT NULL,
	"hstsSubdomains" boolean DEFAULT false NOT NULL,
	"allowWebsocket" boolean DEFAULT true NOT NULL,
	"preserveHostHeader" boolean DEFAULT true NOT NULL,
	"meta" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL,
	"skipHttpsHostnameValidation" boolean DEFAULT false NOT NULL,
	"tags" text DEFAULT '[]' NOT NULL,
	"organizationId" integer
);
--> statement-breakpoint
CREATE TABLE "saml_group_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saml_group_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"providerId" integer NOT NULL,
	"groupValue" text NOT NULL,
	"role" text NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saml_providers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saml_providers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"idpEntityId" text NOT NULL,
	"idpSsoUrl" text NOT NULL,
	"idpCertificates" text NOT NULL,
	"spPrivateKey" text,
	"spCertificate" text,
	"subjectAttribute" text,
	"emailAttribute" text DEFAULT 'email' NOT NULL,
	"nameAttribute" text,
	"groupsAttribute" text,
	"defaultRole" text DEFAULT 'user' NOT NULL,
	"requiredGroup" text,
	"provisionUsers" boolean DEFAULT false NOT NULL,
	"linkExistingAccounts" boolean DEFAULT false NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saml_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saml_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"providerId" integer NOT NULL,
	"requestId" text NOT NULL,
	"bindingHash" text NOT NULL,
	"callbackUrl" text NOT NULL,
	"createdAt" text NOT NULL,
	"expiresAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saml_used_assertions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saml_used_assertions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"providerId" integer NOT NULL,
	"assertionId" text NOT NULL,
	"expiresAt" text NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scim_group_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scim_group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"userId" integer NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scim_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scim_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"externalId" text,
	"origin" text DEFAULT 'scim' NOT NULL,
	"createdByTokenId" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scim_role_mappings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scim_role_mappings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"role" text NOT NULL,
	"customRoleId" integer,
	"priority" integer DEFAULT 100 NOT NULL,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scim_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scim_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"prefix" text NOT NULL,
	"tokenHash" text NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"lastUsedAt" text,
	"expiresAt" text
);
--> statement-breakpoint
CREATE TABLE "scim_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scim_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"userName" text NOT NULL,
	"userNameKey" text NOT NULL,
	"externalId" text,
	"displayName" text,
	"givenName" text,
	"familyName" text,
	"formattedName" text,
	"emails" text DEFAULT '[]' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"origin" text DEFAULT 'scim' NOT NULL,
	"deletedAt" text,
	"linkedAt" text,
	"createdByTokenId" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"token" text NOT NULL,
	"expiresAt" text NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sign_in_sources" (
	"providerId" text PRIMARY KEY NOT NULL,
	"lastSignInAt" text NOT NULL,
	"lastUserId" integer
);
--> statement-breakpoint
CREATE TABLE "two_factors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "two_factors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"secret" text NOT NULL,
	"backupCodes" text NOT NULL,
	"verified" boolean DEFAULT true NOT NULL,
	"failedVerificationCount" integer DEFAULT 0 NOT NULL,
	"lockedUntil" text
);
--> statement-breakpoint
CREATE TABLE "user_preferences" (
	"userId" integer PRIMARY KEY NOT NULL,
	"theme" text DEFAULT 'system' NOT NULL,
	"timeZone" text DEFAULT 'UTC' NOT NULL,
	"numberFormat" text DEFAULT 'en-US' NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"name" text,
	"passwordHash" text,
	"role" text DEFAULT 'user' NOT NULL,
	"provider" text DEFAULT '',
	"subject" text DEFAULT '',
	"avatarUrl" text,
	"status" text DEFAULT 'active' NOT NULL,
	"username" text,
	"displayUsername" text,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"twoFactorEnabled" boolean DEFAULT false NOT NULL,
	"customRoleId" integer,
	"organizationId" integer,
	"lastSignInAt" text,
	"lastSignInMethod" text,
	"disabledAt" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "verifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" text NOT NULL,
	"createdAt" text,
	"updatedAt" text
);
--> statement-breakpoint
CREATE TABLE "virtual_patches" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"severity" text NOT NULL,
	"cves" text DEFAULT '[]' NOT NULL,
	"affected" text DEFAULT '[]' NOT NULL,
	"referenceUrls" text DEFAULT '[]' NOT NULL,
	"rules" text DEFAULT '[]' NOT NULL,
	"ruleIds" text DEFAULT '[]' NOT NULL,
	"samples" text DEFAULT '{"positive":[],"negative":[]}' NOT NULL,
	"defaultMode" text DEFAULT 'detect' NOT NULL,
	"example" boolean DEFAULT false NOT NULL,
	"publishedAt" text NOT NULL,
	"packUpdatedAt" text NOT NULL,
	"mode" text DEFAULT 'off' NOT NULL,
	"modeChangedAt" text,
	"feedSequence" bigint,
	"withdrawnAt" text,
	"firstSeenAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "waf_log_parse_state" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "waf_rule_exclusions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "waf_rule_exclusions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruleId" integer NOT NULL,
	"proxyHostId" integer,
	"pathMatch" text,
	"path" text,
	"variable" text,
	"reason" text DEFAULT '' NOT NULL,
	"createdBy" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "waf_tuning_suggestions" (
	"id" text PRIMARY KEY NOT NULL,
	"host" text NOT NULL,
	"ruleId" integer NOT NULL,
	"proxyHostId" integer NOT NULL,
	"status" text NOT NULL,
	"confidence" text NOT NULL,
	"score" integer NOT NULL,
	"data" text NOT NULL,
	"explanation" text,
	"generatedAt" text NOT NULL,
	"decidedAt" text,
	"decidedBy" integer
);
--> statement-breakpoint
CREATE INDEX "access_list_entries_list_idx" ON "access_list_entries" USING btree ("accessListId");--> statement-breakpoint
CREATE INDEX "access_list_rules_list_position_idx" ON "access_list_rules" USING btree ("accessListId","position");--> statement-breakpoint
CREATE INDEX "access_list_rules_expires_idx" ON "access_list_rules" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "access_lists_system_key_unique" ON "access_lists" USING btree ("systemKey");--> statement-breakpoint
CREATE INDEX "access_lists_organization_idx" ON "access_lists" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "access_review_campaigns_status_idx" ON "access_review_campaigns" USING btree ("status");--> statement-breakpoint
CREATE INDEX "access_review_items_campaign_idx" ON "access_review_items" USING btree ("campaignId","subjectUserId");--> statement-breakpoint
CREATE UNIQUE INDEX "accounts_issuer_account_idx" ON "accounts" USING btree ("issuer","accountId");--> statement-breakpoint
CREATE INDEX "accounts_user_idx" ON "accounts" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "alert_events_created_at_idx" ON "alert_events" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "alert_events_rule_idx" ON "alert_events" USING btree ("ruleId");--> statement-breakpoint
CREATE UNIQUE INDEX "alert_rule_states_rule_subject_unique" ON "alert_rule_states" USING btree ("ruleId","subjectKey");--> statement-breakpoint
CREATE INDEX "analytics_questions_user_idx" ON "analytics_questions" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "analytics_questions_shared_idx" ON "analytics_questions" USING btree ("organizationId","shared");--> statement-breakpoint
CREATE INDEX "analytics_saved_views_user_idx" ON "analytics_saved_views" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "analytics_saved_views_shared_idx" ON "analytics_saved_views" USING btree ("organizationId","shared");--> statement-breakpoint
CREATE UNIQUE INDEX "api_tokens_token_hash_unique" ON "api_tokens" USING btree ("tokenHash");--> statement-breakpoint
CREATE UNIQUE INDEX "approval_policies_name_unique" ON "approval_policies" USING btree ("name");--> statement-breakpoint
CREATE INDEX "audit_events_created_at_idx" ON "audit_events" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "audit_events_organization_idx" ON "audit_events" USING btree ("organizationId","id");--> statement-breakpoint
CREATE INDEX "audit_events_config_after_idx" ON "audit_events" USING btree ("configAfterId");--> statement-breakpoint
CREATE INDEX "audit_events_user_idx" ON "audit_events" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "audit_events_entity_idx" ON "audit_events" USING btree ("entityType","entityId");--> statement-breakpoint
CREATE INDEX "backup_runs_destination_idx" ON "backup_runs" USING btree ("destinationId","id");--> statement-breakpoint
CREATE INDEX "backup_runs_started_at_idx" ON "backup_runs" USING btree ("startedAt");--> statement-breakpoint
CREATE INDEX "certificates_organization_idx" ON "certificates" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "change_request_reviews_request_idx" ON "change_request_reviews" USING btree ("requestId","id");--> statement-breakpoint
CREATE INDEX "change_requests_status_idx" ON "change_requests" USING btree ("status","id");--> statement-breakpoint
CREATE INDEX "change_requests_target_idx" ON "change_requests" USING btree ("targetType","targetId");--> statement-breakpoint
CREATE INDEX "compliance_incidents_detected_at_idx" ON "compliance_incidents" USING btree ("detectedAt");--> statement-breakpoint
CREATE UNIQUE INDEX "compliance_reports_uid_unique" ON "compliance_reports" USING btree ("uid");--> statement-breakpoint
CREATE INDEX "compliance_reports_generated_at_idx" ON "compliance_reports" USING btree ("generatedAt");--> statement-breakpoint
CREATE INDEX "compliance_reports_type_idx" ON "compliance_reports" USING btree ("type");--> statement-breakpoint
CREATE INDEX "compliance_reports_pack_idx" ON "compliance_reports" USING btree ("packId");--> statement-breakpoint
CREATE INDEX "compliance_restore_tests_tested_at_idx" ON "compliance_restore_tests" USING btree ("testedAt");--> statement-breakpoint
CREATE INDEX "config_snapshots_created_at_idx" ON "config_snapshots" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "custom_roles_name_unique" ON "custom_roles" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "fleet_environments_name_unique" ON "fleet_environments" USING btree ("name");--> statement-breakpoint
CREATE INDEX "fleet_instances_environment_idx" ON "fleet_instances" USING btree ("environmentId");--> statement-breakpoint
CREATE UNIQUE INDEX "fleet_pull_replicas_credential_hash_unique" ON "fleet_pull_replicas" USING btree ("credentialHash");--> statement-breakpoint
CREATE INDEX "fleet_revisions_fingerprint_idx" ON "fleet_revisions" USING btree ("fingerprint");--> statement-breakpoint
CREATE UNIQUE INDEX "fleet_rollout_targets_rollout_instance_unique" ON "fleet_rollout_targets" USING btree ("rolloutId","instanceId");--> statement-breakpoint
CREATE INDEX "fleet_rollouts_environment_idx" ON "fleet_rollouts" USING btree ("environmentId","id");--> statement-breakpoint
CREATE INDEX "fleet_rollouts_status_idx" ON "fleet_rollouts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "faa_host_idx" ON "forward_auth_access" USING btree ("proxyHostId");--> statement-breakpoint
CREATE UNIQUE INDEX "faa_user_unique" ON "forward_auth_access" USING btree ("proxyHostId","userId");--> statement-breakpoint
CREATE UNIQUE INDEX "faa_group_unique" ON "forward_auth_access" USING btree ("proxyHostId","groupId");--> statement-breakpoint
CREATE UNIQUE INDEX "fae_code_hash_unique" ON "forward_auth_exchanges" USING btree ("codeHash");--> statement-breakpoint
CREATE UNIQUE INDEX "fari_rid_hash_unique" ON "forward_auth_redirect_intents" USING btree ("ridHash");--> statement-breakpoint
CREATE INDEX "fari_expires_idx" ON "forward_auth_redirect_intents" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "fas_token_hash_unique" ON "forward_auth_sessions" USING btree ("tokenHash");--> statement-breakpoint
CREATE INDEX "fas_user_idx" ON "forward_auth_sessions" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "fas_proxy_host_idx" ON "forward_auth_sessions" USING btree ("proxyHostId");--> statement-breakpoint
CREATE INDEX "fas_expires_idx" ON "forward_auth_sessions" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "group_members_unique" ON "group_members" USING btree ("groupId","userId");--> statement-breakpoint
CREATE INDEX "group_members_user_idx" ON "group_members" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "groups_organization_name_unique" ON "groups" USING btree (coalesce("organizationId", 0),"name");--> statement-breakpoint
CREATE UNIQUE INDEX "instances_base_url_unique" ON "instances" USING btree ("baseUrl");--> statement-breakpoint
CREATE INDEX "issued_client_certificates_ca_idx" ON "issued_client_certificates" USING btree ("caCertificateId");--> statement-breakpoint
CREATE INDEX "issued_client_certificates_revoked_at_idx" ON "issued_client_certificates" USING btree ("revokedAt");--> statement-breakpoint
CREATE UNIQUE INDEX "ldap_directories_name_unique" ON "ldap_directories" USING btree ("name");--> statement-breakpoint
CREATE INDEX "linking_tokens_expires_at_idx" ON "linking_tokens" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_consumers_portal_token_unique" ON "monetization_consumers" USING btree ("portalTokenHash");--> statement-breakpoint
CREATE INDEX "monetization_consumers_plan_idx" ON "monetization_consumers" USING btree ("planId");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_keys_prefix_unique" ON "monetization_keys" USING btree ("prefix");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_keys_key_hash_unique" ON "monetization_keys" USING btree ("keyHash");--> statement-breakpoint
CREATE INDEX "monetization_keys_consumer_idx" ON "monetization_keys" USING btree ("consumerId");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_ledger_external_reference_unique" ON "monetization_ledger" USING btree ("externalReference");--> statement-breakpoint
CREATE INDEX "monetization_ledger_consumer_idx" ON "monetization_ledger" USING btree ("consumerId","id");--> statement-breakpoint
CREATE INDEX "monetization_ledger_created_at_idx" ON "monetization_ledger" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_plans_name_unique" ON "monetization_plans" USING btree ("name");--> statement-breakpoint
CREATE INDEX "mtls_access_rules_proxy_host_idx" ON "mtls_access_rules" USING btree ("proxyHostId");--> statement-breakpoint
CREATE UNIQUE INDEX "mtls_access_rules_host_path_unique" ON "mtls_access_rules" USING btree ("proxyHostId","pathPattern");--> statement-breakpoint
CREATE UNIQUE INDEX "mtls_cert_role_unique" ON "mtls_certificate_roles" USING btree ("issuedClientCertificateId","mtlsRoleId");--> statement-breakpoint
CREATE INDEX "mtls_certificate_roles_role_idx" ON "mtls_certificate_roles" USING btree ("mtlsRoleId");--> statement-breakpoint
CREATE UNIQUE INDEX "mtls_roles_name_unique" ON "mtls_roles" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_providers_name_unique" ON "oauth_providers" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_state_unique" ON "oauth_states" USING btree ("state");--> statement-breakpoint
CREATE UNIQUE INDEX "organizations_slug_unique" ON "organizations" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "passkeys_credential_id_unique" ON "passkeys" USING btree ("credentialID");--> statement-breakpoint
CREATE INDEX "passkeys_user_idx" ON "passkeys" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "pending_oauth_user_provider_unique" ON "pending_oauth_links" USING btree ("userId","provider");--> statement-breakpoint
CREATE INDEX "proxy_hosts_organization_idx" ON "proxy_hosts" USING btree ("organizationId");--> statement-breakpoint
CREATE UNIQUE INDEX "saml_group_roles_provider_group_unique" ON "saml_group_roles" USING btree ("providerId","groupValue");--> statement-breakpoint
CREATE UNIQUE INDEX "saml_providers_name_unique" ON "saml_providers" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "saml_requests_request_id_unique" ON "saml_requests" USING btree ("requestId");--> statement-breakpoint
CREATE UNIQUE INDEX "saml_requests_binding_unique" ON "saml_requests" USING btree ("bindingHash");--> statement-breakpoint
CREATE INDEX "saml_requests_expires_idx" ON "saml_requests" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "saml_used_assertions_unique" ON "saml_used_assertions" USING btree ("providerId","assertionId");--> statement-breakpoint
CREATE INDEX "saml_used_assertions_expires_idx" ON "saml_used_assertions" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "scim_group_members_unique" ON "scim_group_members" USING btree ("groupId","userId");--> statement-breakpoint
CREATE INDEX "scim_group_members_user_idx" ON "scim_group_members" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "scim_groups_group_unique" ON "scim_groups" USING btree ("groupId");--> statement-breakpoint
CREATE UNIQUE INDEX "scim_role_mappings_group_unique" ON "scim_role_mappings" USING btree ("groupId");--> statement-breakpoint
CREATE UNIQUE INDEX "scim_tokens_token_hash_unique" ON "scim_tokens" USING btree ("tokenHash");--> statement-breakpoint
CREATE UNIQUE INDEX "scim_users_user_unique" ON "scim_users" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "scim_users_user_name_key_unique" ON "scim_users" USING btree ("userNameKey");--> statement-breakpoint
CREATE INDEX "scim_users_external_id_idx" ON "scim_users" USING btree ("externalId");--> statement-breakpoint
CREATE UNIQUE INDEX "sessions_token_unique" ON "sessions" USING btree ("token");--> statement-breakpoint
CREATE INDEX "sessions_user_idx" ON "sessions" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "two_factors_user_unique" ON "two_factors" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_unique" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_organization_idx" ON "users" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "waf_rule_exclusions_host_idx" ON "waf_rule_exclusions" USING btree ("proxyHostId");--> statement-breakpoint
CREATE UNIQUE INDEX "waf_tuning_suggestions_host_rule_unique" ON "waf_tuning_suggestions" USING btree ("host","ruleId");--> statement-breakpoint
CREATE INDEX "waf_tuning_suggestions_status_idx" ON "waf_tuning_suggestions" USING btree ("status");
--> statement-breakpoint
-- Not expressed by the Drizzle schema.
-- forward_auth_access (drizzle/0017): a row grants a host to one user or to
-- one group, never both and never neither.
ALTER TABLE "forward_auth_access" ADD CONSTRAINT "forward_auth_access_user_or_group_check" CHECK (("userId" IS NOT NULL AND "groupId" IS NULL) OR ("userId" IS NULL AND "groupId" IS NOT NULL));
--> statement-breakpoint
-- users (drizzle/0041): an organisation user is never the provider's built-in
-- administrator ("admin"), and only organisation users are organisation
-- administrators ("org_admin"). The application refuses both first; these
-- triggers stop any code path that would not. SQLite raises ABORT with the
-- same message; here it is a check_violation (SQLSTATE 23514).
CREATE FUNCTION "users_organization_role_guard"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
	IF (NEW."organizationId" IS NOT NULL AND NEW."role" = 'admin')
		OR (NEW."organizationId" IS NULL AND NEW."role" = 'org_admin') THEN
		RAISE EXCEPTION 'organization role mismatch' USING ERRCODE = 'check_violation';
	END IF;
	RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "users_organization_role_insert" BEFORE INSERT ON "users"
	FOR EACH ROW EXECUTE FUNCTION "users_organization_role_guard"();
--> statement-breakpoint
CREATE TRIGGER "users_organization_role_update" BEFORE UPDATE OF "role", "organizationId" ON "users"
	FOR EACH ROW EXECUTE FUNCTION "users_organization_role_guard"();
--> statement-breakpoint
-- users.disabledAt (drizzle/0047): when the account was disabled, null while
-- it is not, kept whichever way the status changes; an account inserted
-- disabled keeps the disabledAt the insert gives. The value has the format of
-- the application's timestamps (Date.toISOString()). SQLite's AFTER triggers
-- update the row they fired for; a BEFORE trigger sets the value on the row
-- being written, with the same result.
CREATE FUNCTION "users_disabled_at_stamp"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
	NEW."disabledAt" := CASE
		WHEN NEW."status" = 'disabled' THEN to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
	END;
	RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "users_disabled_at_insert" BEFORE INSERT ON "users"
	FOR EACH ROW WHEN (NEW."status" = 'disabled' AND NEW."disabledAt" IS NULL)
	EXECUTE FUNCTION "users_disabled_at_stamp"();
--> statement-breakpoint
CREATE TRIGGER "users_disabled_at_update" BEFORE UPDATE OF "status" ON "users"
	FOR EACH ROW WHEN (NEW."status" IS DISTINCT FROM OLD."status")
	EXECUTE FUNCTION "users_disabled_at_stamp"();
