-- Shared runtime state (drizzle/0054_shared_runtime_state.sql has the same
-- tables for SQLite, where they stay empty): the rate limiter counters, Better
-- Auth's request rate limits and short-lived values one request leaves for a
-- later one, shared by every web replica on this database. Expired rows are
-- pruned by a background job.
CREATE TABLE "auth_rate_limits" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_rate_limits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"count" integer NOT NULL,
	"lastRequest" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rate_limit_counters" (
	"bucket" text PRIMARY KEY NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"windowStartMs" bigint NOT NULL,
	"blockedUntilMs" bigint DEFAULT 0 NOT NULL,
	"held" integer DEFAULT 0 NOT NULL,
	"heldUntilMs" bigint DEFAULT 0 NOT NULL,
	"expiresAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shared_runtime_entries" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"expiresAt" text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "auth_rate_limits_key_unique" ON "auth_rate_limits" USING btree ("key");--> statement-breakpoint
CREATE INDEX "auth_rate_limits_last_request_idx" ON "auth_rate_limits" USING btree ("lastRequest");--> statement-breakpoint
CREATE INDEX "rate_limit_counters_expires_idx" ON "rate_limit_counters" USING btree ("expiresAtMs");--> statement-breakpoint
CREATE INDEX "shared_runtime_entries_expires_idx" ON "shared_runtime_entries" USING btree ("expiresAt");
