-- API monetization, phase 2 (drizzle/0056_monetization_phase2.sql has the same
-- change for SQLite): postpaid billing, failed-answer credits, Stripe
-- payments, x402 payments.
CREATE TABLE "monetization_answer_credits" (
	"chargeId" text PRIMARY KEY NOT NULL,
	"consumerId" integer NOT NULL,
	"amountMicros" bigint NOT NULL,
	"free" boolean DEFAULT false NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monetization_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"consumerId" integer NOT NULL,
	"kind" text NOT NULL,
	"reason" text,
	"status" text NOT NULL,
	"amountMicros" bigint NOT NULL,
	"currency" text NOT NULL,
	"period" text,
	"idempotencyKey" text,
	"paymentMethodId" text,
	"paymentIntentId" text,
	"checkoutSessionId" text,
	"failureCode" text,
	"refundedMicros" bigint DEFAULT 0 NOT NULL,
	"disputedMicros" bigint DEFAULT 0 NOT NULL,
	"ledgerId" integer,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_x402_payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monetization_x402_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proxyHostId" integer NOT NULL,
	"consumerId" integer,
	"payer" text NOT NULL,
	"network" text NOT NULL,
	"asset" text NOT NULL,
	"amountMicros" bigint NOT NULL,
	"nonceKey" text NOT NULL,
	"status" text NOT NULL,
	"transaction" text,
	"paymentIntentId" text,
	"recordAttempts" integer DEFAULT 0 NOT NULL,
	"errorReason" text,
	"createdAt" text NOT NULL,
	"updatedAt" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "billing" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "stripeCustomerId" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "paymentMethodId" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "cardBrand" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "cardLast4" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "cardExpMonth" integer;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "cardExpYear" integer;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "suspendedAt" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "suspendedReason" text;--> statement-breakpoint
ALTER TABLE "monetization_consumers" ADD COLUMN "billedPeriod" text;--> statement-breakpoint
ALTER TABLE "monetization_hosts" ADD COLUMN "x402Enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "monetization_hosts" ADD COLUMN "x402PriceCents" integer;--> statement-breakpoint
ALTER TABLE "monetization_plans" ADD COLUMN "billing" text DEFAULT 'prepaid' NOT NULL;--> statement-breakpoint
ALTER TABLE "monetization_plans" ADD COLUMN "postpaidCapMicros" bigint;--> statement-breakpoint
ALTER TABLE "monetization_plans" ADD COLUMN "postpaidThresholdMicros" bigint;--> statement-breakpoint
ALTER TABLE "monetization_plans" ADD COLUMN "creditFailedAnswers" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "monetization_plans" ADD COLUMN "acceptX402" boolean DEFAULT false NOT NULL;--> statement-breakpoint
CREATE INDEX "monetization_answer_credits_created_at_idx" ON "monetization_answer_credits" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_payments_idempotency_key_unique" ON "monetization_payments" USING btree ("idempotencyKey");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_payments_payment_intent_unique" ON "monetization_payments" USING btree ("paymentIntentId");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_payments_checkout_session_unique" ON "monetization_payments" USING btree ("checkoutSessionId");--> statement-breakpoint
CREATE INDEX "monetization_payments_consumer_idx" ON "monetization_payments" USING btree ("consumerId","id");--> statement-breakpoint
CREATE INDEX "monetization_payments_status_idx" ON "monetization_payments" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_x402_payments_nonce_key_unique" ON "monetization_x402_payments" USING btree ("nonceKey");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_x402_payments_transaction_unique" ON "monetization_x402_payments" USING btree ("network","transaction");--> statement-breakpoint
CREATE UNIQUE INDEX "monetization_x402_payments_payment_intent_unique" ON "monetization_x402_payments" USING btree ("paymentIntentId");--> statement-breakpoint
CREATE INDEX "monetization_x402_payments_created_at_idx" ON "monetization_x402_payments" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "monetization_x402_payments_payer_idx" ON "monetization_x402_payments" USING btree ("payer");