-- Dismissing and muting alerts (drizzle/0058_alert_silences.sql has the same
-- change for SQLite): alert_silences, and alert_events.silenced for firing
-- notifications a mute or dismissal held back.
CREATE TABLE "alert_silences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_silences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruleId" integer NOT NULL,
	"subjectKey" text,
	"until" text,
	"note" text,
	"createdBy" integer,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "alert_events" ADD COLUMN "silenced" text;--> statement-breakpoint
CREATE INDEX "alert_silences_rule_idx" ON "alert_silences" USING btree ("ruleId","subjectKey");
