// SPDX-License-Identifier: Elastic-2.0
/**
 * Generating, storing, reading and exporting compliance reports.
 *
 * Licensing: generating a report needs "compliance_reports"; reading,
 * downloading and deleting stored reports never do.
 *
 * Integrity: a report is stored as its canonical JSON (canonical.ts) with
 * the SHA-256 of that text, and generation records the SHA-256 in the
 * hash-chained audit log, so a stored or downloaded report can later be
 * checked against a record that cannot be changed unnoticed.
 */
import { randomUUID } from "node:crypto";
import { and, count, eq, gte } from "drizzle-orm";
import { appDb } from "@/src/lib/db";
import { auditEvents, complianceReports, users } from "@/src/lib/db/schema";
import { logAuditEvent } from "@/src/lib/audit";
import { ApiClientError, ApiValidationError } from "@/src/lib/api-errors";
import { APP_VERSION } from "@/src/lib/app-version";
import { BRAND_NAME } from "@/src/lib/brand";
import { getInstanceMode } from "@/src/lib/instance-sync";
import { requireFeature } from "@/ee/licensing/store";
import { csvCell } from "@/ee/audit/export";
import { CANONICALIZATION, canonicalJson, sha256Hex } from "./canonical";
import { COMPLIANCE_STATEMENT, controlsFor } from "./controls";
import { parsePeriod, rejectUnknownKeys, requireRecord } from "./http";
import { buildAccessReview } from "./reports/access-review";
import { buildChangeLog } from "./reports/change-log";
import { buildCertificateInventory } from "./reports/certificate-inventory";
import { buildProtectionCoverage } from "./reports/protection-coverage";
import { buildTrafficQuestions } from "./reports/traffic-questions";
import { countFindings, defaultAnalytics, type AnalyticsDependencies, type ReportBuilder } from "./reports/shared";
import {
  FEATURE,
  FINDING_SEVERITIES,
  REPORT_TYPE_LABELS,
  SELECTABLE_REPORT_TYPES,
  isReportType,
  isSelectableReportType,
  type ComplianceReportDocument,
  type FindingCounts,
  type ReportCell,
  type ReportIntegrity,
  type ReportListPage,
  type ReportType,
  type ScheduleQuestion,
  type StoredReportDetail,
  type StoredReportSummary,
} from "./types";
import { desc, first } from "@/src/lib/db/ops";

export const REPORT_NOT_FOUND = "Report not found";
export const DEFAULT_PERIOD_DAYS = 30;
export const MAX_PERIOD_DAYS = 366;
export const REPORT_FORMATS = ["json", "csv"] as const;
export type ReportFormat = (typeof REPORT_FORMATS)[number];

const BUILDERS: Record<ReportType, ReportBuilder> = {
  access_review: buildAccessReview,
  change_log: buildChangeLog,
  certificate_inventory: buildCertificateInventory,
  protection_coverage: buildProtectionCoverage,
  traffic_questions: buildTrafficQuestions,
};

/**
 * Report types built from the database alone (no ClickHouse, no network), so
 * from one read-only snapshot. The change log is not: verifying the audit
 * chain is long work that would hold SQLite's gate.
 */
const SNAPSHOT_REPORT_TYPES: ReadonlySet<ReportType> = new Set<ReportType>(["access_review", "certificate_inventory"]);

export type ReportDependencies = {
  now: () => Date;
  analytics: AnalyticsDependencies;
  uuid: () => string;
};

function dependencies(overrides: Partial<ReportDependencies> = {}): ReportDependencies {
  return {
    now: overrides.now ?? (() => new Date()),
    analytics: overrides.analytics ?? defaultAnalytics,
    uuid: overrides.uuid ?? randomUUID,
  };
}

type ReportRow = typeof complianceReports.$inferSelect;

export type GenerateInput = { type: ReportType; from: Date; to: Date; format: ReportFormat };

export function parseGenerateInput(body: unknown, now: Date): GenerateInput {
  const record = requireRecord(body);
  rejectUnknownKeys(record, ["type", "from", "to", "format"], "the report request");
  if (record.type === "traffic_questions") {
    throw new ApiValidationError("Traffic questions reports are generated by report schedules: add saved questions to a schedule and run it");
  }
  if (!isSelectableReportType(record.type)) throw new ApiValidationError(`type must be one of: ${SELECTABLE_REPORT_TYPES.join(", ")}`);
  const format = record.format === undefined ? "json" : record.format;
  if (!(REPORT_FORMATS as readonly unknown[]).includes(format)) throw new ApiValidationError("format must be json or csv");
  const period = parsePeriod(record, now, { defaultDays: DEFAULT_PERIOD_DAYS, maxDays: MAX_PERIOD_DAYS });
  return { type: record.type, from: period.from, to: period.to, format: format as ReportFormat };
}

function parseCounts(value: string): FindingCounts {
  const counts: FindingCounts = { high: 0, medium: 0, low: 0, info: 0 };
  try {
    const parsed = JSON.parse(value) as Record<string, unknown>;
    for (const severity of FINDING_SEVERITIES) {
      if (typeof parsed[severity] === "number") counts[severity] = parsed[severity] as number;
    }
  } catch {
    // keep zeros
  }
  return counts;
}

function toSummary(row: ReportRow): StoredReportSummary {
  const type = isReportType(row.type) ? row.type : "access_review";
  return {
    id: row.id,
    reportId: row.uid,
    type,
    title: REPORT_TYPE_LABELS[type],
    period: { from: row.periodFrom, to: row.periodTo },
    generatedAt: row.generatedAt,
    generatedBy: { userId: row.generatedBy, name: row.generatedByName },
    sha256: row.sha256,
    findings: parseCounts(row.findingCounts),
    sizeBytes: row.sizeBytes,
    scheduleId: row.scheduleId ?? null,
    packId: row.packId ?? null,
  };
}

async function requireRow(id: number): Promise<ReportRow> {
  const row = await first(appDb.select().from(complianceReports).where(eq(complianceReports.id, id)).limit(1));
  if (!row) throw new ApiClientError(REPORT_NOT_FOUND, 404);
  return row;
}

/** Who generated a report: a user, or a schedule (userId null, name "Schedule ..."). */
export type ReportGenerator = { userId: number | null; name: string | null; email: string | null };

/** Builds the report document for the period (no license check, nothing stored). */
export async function buildReportDocument(
  input: { type: ReportType; from: Date; to: Date; questions?: readonly ScheduleQuestion[] },
  generator: ReportGenerator,
  overrides: Partial<ReportDependencies> = {}
): Promise<ComplianceReportDocument> {
  const deps = dependencies(overrides);
  const now = deps.now();
  const build = () => BUILDERS[input.type]({ period: { from: input.from, to: input.to }, now, analytics: deps.analytics, questions: input.questions });
  // A report built from the database alone reads it in one read-only snapshot.
  const built = SNAPSHOT_REPORT_TYPES.has(input.type) ? await appDb.transaction(build, { readOnly: true }) : await build();
  return {
    format: "compliance-report",
    formatVersion: 1,
    reportId: deps.uuid(),
    type: input.type,
    title: REPORT_TYPE_LABELS[input.type],
    period: { from: input.from.toISOString(), to: input.to.toISOString() },
    generatedAt: now.toISOString(),
    generatedBy: generator,
    product: { name: BRAND_NAME, version: APP_VERSION },
    instanceMode: await getInstanceMode(),
    statement: COMPLIANCE_STATEMENT,
    controls: controlsFor(input.type),
    summary: built.summary,
    findings: built.findings,
    sections: built.sections,
    notes: built.notes,
  };
}

async function generatorOf(userId: number): Promise<{ userId: number; name: string | null; email: string | null }> {
  const user = await first(appDb.select({ name: users.name, email: users.email, username: users.username }).from(users).where(eq(users.id, userId)).limit(1));
  return { userId, name: user?.name ?? user?.username ?? null, email: user?.email ?? null };
}

/**
 * Stores a built report and records its SHA-256 in the audit log (by the
 * user, or by no user for a schedule). No license check.
 */
export async function storeReportDocument(
  document: ComplianceReportDocument,
  options: { actorUserId: number | null; scheduleId?: number | null; packId?: string | null }
): Promise<StoredReportDetail> {
  const content = canonicalJson(document);
  const sha256 = sha256Hex(content);
  const counts = countFindings(document.findings);
  const row = (await first(appDb
    .insert(complianceReports)
    .values({
      uid: document.reportId,
      type: document.type,
      periodFrom: document.period.from,
      periodTo: document.period.to,
      generatedAt: document.generatedAt,
      generatedBy: options.actorUserId,
      generatedByName: document.generatedBy.name ?? document.generatedBy.email,
      sha256,
      findingCounts: JSON.stringify(counts),
      sizeBytes: Buffer.byteLength(content, "utf8"),
      content,
      scheduleId: options.scheduleId ?? null,
      packId: options.packId ?? null,
    })
    .returning()))!;
  await logAuditEvent({
    userId: options.actorUserId,
    action: "compliance_report_generated",
    entityType: "compliance_report",
    entityId: row.id,
    summary: `Generated the ${REPORT_TYPE_LABELS[document.type].toLowerCase()} report for ${document.period.from.slice(0, 10)} to ${document.period.to.slice(0, 10)} (SHA-256 ${sha256.slice(0, 16)}…)`,
    data: {
      reportId: document.reportId,
      type: document.type,
      from: document.period.from,
      to: document.period.to,
      sha256,
      findings: counts,
      ...(options.scheduleId ? { scheduleId: options.scheduleId, packId: options.packId ?? null } : {}),
    },
  });
  return { ...toSummary(row), document, integrity: await integrityOf(row) };
}

/** Generates, stores and audits a report. Needs the compliance_reports feature. */
export async function generateReport(
  body: unknown,
  actorUserId: number,
  overrides: Partial<ReportDependencies> = {}
): Promise<{ detail: StoredReportDetail; format: ReportFormat }> {
  await requireFeature(FEATURE);
  const deps = dependencies(overrides);
  const input = parseGenerateInput(body, deps.now());
  const document = await buildReportDocument(input, await generatorOf(actorUserId), deps);
  return { detail: await storeReportDocument(document, { actorUserId }), format: input.format };
}

export async function listReports(options: { type?: ReportType | null; packId?: string | null; page: number; perPage: number }): Promise<ReportListPage> {
  const where = and(
    options.type ? eq(complianceReports.type, options.type) : undefined,
    options.packId ? eq(complianceReports.packId, options.packId) : undefined
  );
  const rows = await appDb
    .select({
      id: complianceReports.id,
      uid: complianceReports.uid,
      type: complianceReports.type,
      periodFrom: complianceReports.periodFrom,
      periodTo: complianceReports.periodTo,
      generatedAt: complianceReports.generatedAt,
      generatedBy: complianceReports.generatedBy,
      generatedByName: complianceReports.generatedByName,
      sha256: complianceReports.sha256,
      findingCounts: complianceReports.findingCounts,
      sizeBytes: complianceReports.sizeBytes,
      scheduleId: complianceReports.scheduleId,
      packId: complianceReports.packId,
    })
    .from(complianceReports)
    .where(where)
    .orderBy(desc(complianceReports.generatedAt), desc(complianceReports.id))
    .limit(options.perPage)
    .offset((options.page - 1) * options.perPage);
  const total = (await first(appDb.select({ value: count() }).from(complianceReports).where(where).limit(1)))?.value ?? 0;
  return { reports: rows.map((row) => toSummary({ ...row, content: "" })), total, page: options.page, perPage: options.perPage };
}

/** The stored content re-hashed, and the audit event recorded at generation. */
async function integrityOf(row: ReportRow): Promise<ReportIntegrity> {
  const recomputed = sha256Hex(row.content);
  const event = await first(appDb
    .select({ id: auditEvents.id, createdAt: auditEvents.createdAt, data: auditEvents.data })
    .from(auditEvents)
    .where(
      and(
        // Recorded after generation started; the bound lets SQLite use the createdAt index.
        gte(auditEvents.createdAt, row.generatedAt),
        eq(auditEvents.entityType, "compliance_report"),
        eq(auditEvents.entityId, row.id),
        eq(auditEvents.action, "compliance_report_generated")
      )
    )
    .orderBy(desc(auditEvents.id))
    .limit(1));
  let auditEvent: ReportIntegrity["auditEvent"] = null;
  if (event) {
    let recorded: unknown;
    try {
      recorded = event.data ? (JSON.parse(event.data) as { sha256?: unknown }).sha256 : null;
    } catch {
      recorded = null;
    }
    auditEvent = { id: event.id, recordedAt: event.createdAt, sha256Matches: recorded === row.sha256 && recorded === recomputed };
  }
  return { algorithm: "SHA-256", canonicalization: CANONICALIZATION, sha256: row.sha256, contentMatches: recomputed === row.sha256, auditEvent };
}

function parseDocument(row: ReportRow): ComplianceReportDocument {
  try {
    return JSON.parse(row.content) as ComplianceReportDocument;
  } catch {
    throw new ApiClientError("The stored report cannot be read", 409);
  }
}

export async function getReport(id: number): Promise<StoredReportDetail> {
  const row = await requireRow(id);
  return { ...toSummary(row), document: parseDocument(row), integrity: await integrityOf(row) };
}

/** Never needs a license. */
export async function deleteReport(id: number, actorUserId: number): Promise<void> {
  const row = await requireRow(id);
  await appDb.delete(complianceReports).where(eq(complianceReports.id, id));
  await logAuditEvent({
    userId: actorUserId,
    action: "compliance_report_deleted",
    entityType: "compliance_report",
    entityId: id,
    summary: `Deleted the ${REPORT_TYPE_LABELS[isReportType(row.type) ? row.type : "access_review"].toLowerCase()} report generated on ${row.generatedAt.slice(0, 10)}`,
    data: { reportId: row.uid, type: row.type, sha256: row.sha256 },
  });
}

// ── Export ─────────────────────────────────────────────────────────────

export type ReportFile = { body: string; filename: string; contentType: string; sha256: string; reportId: string };

function fileStem(detail: Pick<StoredReportSummary, "type" | "period" | "id">): string {
  return `${detail.type.replace(/_/g, "-")}-${detail.period.from.slice(0, 10)}_${detail.period.to.slice(0, 10)}-${detail.id}`;
}

/** The report with its integrity block, as downloaded. */
export function reportJson(detail: StoredReportDetail): string {
  return `${JSON.stringify(
    { ...detail.document, integrity: { algorithm: "SHA-256", canonicalization: CANONICALIZATION, sha256: detail.sha256 } },
    null,
    2
  )}\n`;
}

function csvValue(value: ReportCell): string {
  if (Array.isArray(value)) return csvCell(value.join("; "));
  if (typeof value === "boolean") return value ? "yes" : "no";
  return csvCell(value);
}

function csvTable(headers: string[], rows: ReportCell[][]): string {
  return [headers.map((header) => csvCell(header)).join(","), ...rows.map((row) => row.map(csvValue).join(","))].join("\r\n") + "\r\n";
}

/** Sections a CSV export can name; "summary" and "findings" exist in every report. */
export function csvSections(document: ComplianceReportDocument): string[] {
  return ["summary", "findings", ...document.sections.map((item) => item.key)];
}

/**
 * One table of the report as CSV: "summary" (report metadata, its SHA-256 and
 * the summary figures), "findings", or a section. Defaults to the report's
 * first section. Cells a spreadsheet would run as formulas are neutralised.
 */
export function reportCsv(detail: StoredReportDetail, sectionKey: string | null): { body: string; section: string } {
  const document = detail.document;
  const key = sectionKey ?? document.sections[0]?.key ?? "summary";
  if (key === "summary") {
    const rows: ReportCell[][] = [
      ["Report", document.title],
      ["Report id", document.reportId],
      ["Period from (UTC)", document.period.from],
      ["Period to (UTC)", document.period.to],
      ["Generated at (UTC)", document.generatedAt],
      ["Generated by", [document.generatedBy.name, document.generatedBy.email].filter(Boolean).join(" ") || `user ${document.generatedBy.userId}`],
      ["Product", `${document.product.name} ${document.product.version}`],
      ["SHA-256 of the JSON report (canonical)", detail.sha256],
      ["Statement", document.statement],
      ...document.controls.map((control): ReportCell[] => [`Supports ${control.framework} ${control.ref}`, `${control.title}: ${control.how}`]),
      ...document.summary.map((item): ReportCell[] => [item.label, item.value]),
    ];
    return { body: csvTable(["Item", "Value"], rows), section: key };
  }
  if (key === "findings") {
    return {
      body: csvTable(["Severity", "Code", "Subject", "Message"], document.findings.map((item) => [item.severity, item.code, item.subject, item.message])),
      section: key,
    };
  }
  const found = document.sections.find((item) => item.key === key);
  if (!found) throw new ApiValidationError(`section must be one of: ${csvSections(document).join(", ")}`);
  return {
    body: csvTable(found.columns.map((column) => column.label), found.rows.map((row) => found.columns.map((column) => row[column.key] ?? null))),
    section: key,
  };
}

export function reportFile(detail: StoredReportDetail, format: ReportFormat, sectionKey: string | null): ReportFile {
  if (format === "json") {
    return {
      body: reportJson(detail),
      filename: `${fileStem(detail)}.json`,
      contentType: "application/json; charset=utf-8",
      sha256: detail.sha256,
      reportId: detail.reportId,
    };
  }
  const csv = reportCsv(detail, sectionKey);
  return {
    body: csv.body,
    filename: `${fileStem(detail)}-${csv.section.replace(/_/g, "-")}.csv`,
    contentType: "text/csv; charset=utf-8",
    sha256: detail.sha256,
    reportId: detail.reportId,
  };
}

export function parseExportQuery(params: URLSearchParams): { format: ReportFormat; section: string | null } {
  const format = (params.get("format") ?? "json").trim().toLowerCase();
  if (!(REPORT_FORMATS as readonly string[]).includes(format)) throw new ApiValidationError("format must be json or csv");
  const section = params.get("section");
  if (section !== null && !/^[a-z_]{1,64}$/.test(section)) throw new ApiValidationError("section must be a section key of the report");
  return { format: format as ReportFormat, section };
}

export function fileHeaders(file: ReportFile): Record<string, string> {
  return {
    "Content-Type": file.contentType,
    "Content-Disposition": `attachment; filename="${file.filename}"`,
    "Cache-Control": "no-store",
    "X-Content-Type-Options": "nosniff",
    "X-Report-Id": file.reportId,
    "X-Report-Sha256": file.sha256,
  };
}

