// SPDX-License-Identifier: Elastic-2.0
/**
 * Scheduled evidence reports: every week or month, the chosen report types
 * are generated for the period that just ended, stored and hashed exactly
 * like reports generated by hand (with the schedule and a pack id per run),
 * the audit log's hash chain is verified and recorded, and a short notice
 * with the findings and SHA-256 digests goes to the chosen alert channels.
 * Report contents (users, token names, hosts) are never sent: the notice
 * links to the dashboard.
 *
 * Periods, in the schedule's time zone: a weekly run covers the seven days
 * before the day it runs; a monthly run covers the previous calendar month.
 *
 * Saved analytics questions (ee/ai/questions) can be part of a schedule:
 * they are copied into it (question and validated query), and each run adds
 * a "Traffic questions" report that re-runs them for the period. Adding them
 * follows the compliance permissions and license; the copies stay when the
 * saved question or its owner is deleted.
 *
 * Licensing: creating a schedule, changing or enabling one and running one
 * by hand need "compliance_reports"; disabling and deleting never do, and
 * schedules that were set up keep running whatever the license state.
 */
import { randomUUID } from "node:crypto";
import { and, eq, isNotNull, lte } from "drizzle-orm";
import { appDb, nowIso } from "@/src/lib/db";
import { complianceReports, complianceReportSchedules, users } from "@/src/lib/db/schema";
import { logAuditEvent } from "@/src/lib/audit";
import { ApiClientError, ApiValidationError } from "@/src/lib/api-errors";
import { config } from "@/src/lib/config";
import { requireFeature } from "@/ee/licensing/store";
import { isWindDownOnly } from "@/ee/alerting/gate";
import { getChannelTypes } from "@/ee/alerting/channels";
import { sendNotice, type Notice, type NoticeDelivery, type NoticeDependencies } from "@/ee/alerting/notice";
import { nextRunAfter, parseTimeZone, resolveWallTime, wallTime } from "@/ee/backups/schedule";
import { WEEKDAYS, type Weekday } from "@/ee/backups/types";
import { verifyAuditChain } from "@/ee/audit/verify";
import { parseLine, rejectUnknownKeys, requireRecord } from "./http";
import { buildReportDocument, listReports, storeReportDocument, type ReportDependencies } from "./reports";
import { describeSavedQuery, savedQuestionsVisibleTo } from "@/ee/ai/questions/saved";
import { parseQuestionQuery } from "@/ee/ai/questions/schema";
import {
  FEATURE,
  REPORT_TYPE_LABELS,
  REPORT_TYPES,
  SELECTABLE_REPORT_TYPES,
  isSelectableReportType,
  type ReportType,
  type ScheduleQuestion,
  type ScheduleQuestionView,
  type SelectableReportType,
  type StoredReportSummary,
} from "./types";
import { asc, desc, first } from "@/src/lib/db/ops";

export const SCHEDULE_NOT_FOUND = "Report schedule not found";
export const FREQUENCIES = ["weekly", "monthly"] as const;
export type Frequency = (typeof FREQUENCIES)[number];
export const MAX_SCHEDULE_CHANNELS = 20;
export const MAX_SCHEDULES = 20;
export const MAX_SCHEDULE_QUESTIONS = 10;
const TIME = /^([01]\d|2[0-3]):([0-5]\d)$/;
const DAY_MS = 24 * 60 * 60 * 1000;

type ScheduleRow = typeof complianceReportSchedules.$inferSelect;

export type ReportScheduleView = {
  id: number;
  name: string;
  enabled: boolean;
  frequency: Frequency;
  weekday: Weekday | null;
  dayOfMonth: number | null;
  time: string;
  timeZone: string;
  reportTypes: SelectableReportType[];
  /** Saved analytics questions copied into the schedule; each run adds a "Traffic questions" report for them. */
  questions: ScheduleQuestionView[];
  channelIds: number[];
  nextRunAt: string | null;
  /** The period the next run will cover. */
  nextPeriod: { from: string; to: string } | null;
  lastRunAt: string | null;
  lastStatus: "success" | "partial" | "failed" | null;
  lastError: string | null;
  lastPackId: string | null;
  lastDeliveries: NoticeDelivery[];
  /** The reports of the last run. */
  lastReports: StoredReportSummary[];
  createdAt: string;
  updatedAt: string;
};

function parseJsonArray(value: string | null): unknown[] {
  if (!value) return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function storedTypes(row: ScheduleRow): SelectableReportType[] {
  const types = parseJsonArray(row.reportTypes).filter(isSelectableReportType);
  return SELECTABLE_REPORT_TYPES.filter((type) => types.includes(type));
}

/** The questions copied into the schedule, as stored (their queries are validated again when they run). */
function storedQuestions(row: Pick<ScheduleRow, "questions">): ScheduleQuestion[] {
  return parseJsonArray(row.questions ?? "[]")
    .filter((item): item is Record<string, unknown> => typeof item === "object" && item !== null && !Array.isArray(item))
    .filter((item) => typeof item.question === "string")
    .map((item) => ({
      savedQuestionId: Number.isSafeInteger(item.savedQuestionId) && (item.savedQuestionId as number) > 0 ? (item.savedQuestionId as number) : null,
      question: item.question as string,
      query: item.query as ScheduleQuestion["query"],
    }));
}

function questionView(question: ScheduleQuestion): ScheduleQuestionView {
  let interpretation: string;
  try {
    interpretation = describeSavedQuery(parseQuestionQuery(question.query));
  } catch {
    interpretation = "Its stored query is no longer valid";
  }
  return { savedQuestionId: question.savedQuestionId, question: question.question, interpretation };
}

function storedChannels(row: ScheduleRow): number[] {
  return parseJsonArray(row.channelIds).filter((id): id is number => Number.isSafeInteger(id) && (id as number) > 0);
}

function storedDeliveries(row: ScheduleRow): NoticeDelivery[] {
  return parseJsonArray(row.lastDeliveries)
    .filter((item): item is Record<string, unknown> => typeof item === "object" && item !== null)
    .map((item) => ({ channelId: Number(item.channelId), channelName: String(item.channelName ?? ""), ok: item.ok === true, error: typeof item.error === "string" ? item.error : null }));
}

function frequencyOf(row: ScheduleRow): Frequency {
  return row.frequency === "monthly" ? "monthly" : "weekly";
}

function weekdayOf(row: ScheduleRow): Weekday {
  return (WEEKDAYS as readonly string[]).includes(row.weekday ?? "") ? (row.weekday as Weekday) : "monday";
}

// ── Timing ────────────────────────────────────────────────────────────

type Timing = { frequency: Frequency; weekday: Weekday; dayOfMonth: number; time: string; timeZone: string };

function timingOf(row: ScheduleRow): Timing {
  return { frequency: frequencyOf(row), weekday: weekdayOf(row), dayOfMonth: Math.min(28, Math.max(1, row.dayOfMonth ?? 1)), time: row.time, timeZone: row.timeZone };
}

function localMidnight(timeZone: string, date: { year: number; month: number; day: number }): number {
  const { instants, afterGap } = resolveWallTime(timeZone, date, 0, 0);
  return instants.length > 0 ? instants[0] : afterGap;
}

/** The first run strictly after `after`. */
export function nextScheduledRun(timing: Timing, after: Date): Date {
  if (timing.frequency === "weekly") return nextRunAfter({ kind: "weekly", day: timing.weekday, time: timing.time }, timing.timeZone, after);
  const [hour, minute] = timing.time.split(":").map(Number);
  const local = wallTime(timing.timeZone, after.getTime());
  for (let step = 0; step <= 13; step++) {
    const month = ((local.month - 1 + step) % 12) + 1;
    const year = local.year + Math.floor((local.month - 1 + step) / 12);
    const { instants, afterGap } = resolveWallTime(timing.timeZone, { year, month, day: timing.dayOfMonth }, hour, minute);
    const instant = instants.length > 0 ? instants[0] : afterGap;
    if (instant > after.getTime()) return new Date(instant);
  }
  return new Date(after.getTime() + 31 * DAY_MS);
}

/** The period a run at `runAt` covers: the seven days before its local day, or the previous calendar month. */
export function periodOfRun(timing: Timing, runAt: Date): { from: Date; to: Date } {
  const local = wallTime(timing.timeZone, runAt.getTime());
  if (timing.frequency === "weekly") {
    const end = localMidnight(timing.timeZone, local);
    const startDate = new Date(Date.UTC(local.year, local.month - 1, local.day) - 7 * DAY_MS);
    const start = localMidnight(timing.timeZone, { year: startDate.getUTCFullYear(), month: startDate.getUTCMonth() + 1, day: startDate.getUTCDate() });
    return { from: new Date(start), to: new Date(end - 1) };
  }
  const end = localMidnight(timing.timeZone, { year: local.year, month: local.month, day: 1 });
  const previousMonth = local.month === 1 ? 12 : local.month - 1;
  const previousYear = local.month === 1 ? local.year - 1 : local.year;
  const start = localMidnight(timing.timeZone, { year: previousYear, month: previousMonth, day: 1 });
  return { from: new Date(start), to: new Date(end - 1) };
}

// ── Views ─────────────────────────────────────────────────────────────

async function lastReportsOf(packId: string | null): Promise<StoredReportSummary[]> {
  if (!packId) return [];
  const { reports } = await listReports({ packId, page: 1, perPage: REPORT_TYPES.length });
  return reports.sort((a, b) => REPORT_TYPES.indexOf(a.type) - REPORT_TYPES.indexOf(b.type));
}

async function toView(row: ScheduleRow): Promise<ReportScheduleView> {
  const timing = timingOf(row);
  const nextPeriod = row.nextRunAt ? periodOfRun(timing, new Date(row.nextRunAt)) : null;
  return {
    id: row.id,
    name: row.name,
    enabled: row.enabled,
    frequency: timing.frequency,
    weekday: timing.frequency === "weekly" ? timing.weekday : null,
    dayOfMonth: timing.frequency === "monthly" ? timing.dayOfMonth : null,
    time: row.time,
    timeZone: row.timeZone,
    reportTypes: storedTypes(row),
    questions: storedQuestions(row).map(questionView),
    channelIds: storedChannels(row),
    nextRunAt: row.nextRunAt,
    nextPeriod: nextPeriod ? { from: nextPeriod.from.toISOString(), to: nextPeriod.to.toISOString() } : null,
    lastRunAt: row.lastRunAt,
    lastStatus: row.lastStatus === "success" || row.lastStatus === "partial" || row.lastStatus === "failed" ? row.lastStatus : null,
    lastError: row.lastError,
    lastPackId: row.lastPackId,
    lastDeliveries: storedDeliveries(row),
    lastReports: await lastReportsOf(row.lastPackId),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

async function requireRow(id: number): Promise<ScheduleRow> {
  const row = await first(appDb.select().from(complianceReportSchedules).where(eq(complianceReportSchedules.id, id)).limit(1));
  if (!row) throw new ApiClientError(SCHEDULE_NOT_FOUND, 404);
  return row;
}

export async function listReportSchedules(): Promise<ReportScheduleView[]> {
  const rows = await appDb.select().from(complianceReportSchedules).orderBy(asc(complianceReportSchedules.name), asc(complianceReportSchedules.id));
  return Promise.all(rows.map(toView));
}

export async function getReportSchedule(id: number): Promise<ReportScheduleView> {
  return toView(await requireRow(id));
}

// ── Input ─────────────────────────────────────────────────────────────

const FIELDS = ["name", "enabled", "frequency", "weekday", "dayOfMonth", "time", "timeZone", "reportTypes", "questionIds", "channelIds"];

async function readChannelIds(value: unknown): Promise<number[]> {
  if (!Array.isArray(value)) throw new ApiValidationError("channelIds must be an array of alert channel ids");
  if (value.length > MAX_SCHEDULE_CHANNELS) throw new ApiValidationError(`A schedule can notify at most ${MAX_SCHEDULE_CHANNELS} channels`);
  const ids = [...new Set(value.map((id) => {
    if (typeof id !== "number" || !Number.isSafeInteger(id) || id < 1) throw new ApiValidationError("channelIds must be an array of alert channel ids");
    return id;
  }))];
  // Throws a 400 naming a channel that does not exist.
  const types = await getChannelTypes(ids);
  for (const [id, type] of types) {
    if (type === "pagerduty") throw new ApiValidationError(`Channel ${id} is a PagerDuty channel: notices are not sent to PagerDuty`);
  }
  return ids;
}

function readReportTypes(value: unknown): SelectableReportType[] {
  if (!Array.isArray(value)) throw new ApiValidationError("reportTypes must be an array of report types");
  for (const type of value) {
    if (!isSelectableReportType(type)) {
      throw new ApiValidationError(
        type === "traffic_questions"
          ? "Traffic questions are added with questionIds, not as a report type"
          : `reportTypes must contain: ${SELECTABLE_REPORT_TYPES.join(", ")}`
      );
    }
  }
  return SELECTABLE_REPORT_TYPES.filter((type) => (value as unknown[]).includes(type));
}

/**
 * Saved analytics questions to copy into the schedule, by id: the ones the
 * actor can see (their own and the shared ones) are
 * copied as they are now; ids already in the schedule whose saved question
 * is gone or no longer visible keep their copy.
 */
async function readQuestionIds(value: unknown, existing: ScheduleRow | null, actorUserId: number): Promise<ScheduleQuestion[]> {
  if (!Array.isArray(value)) throw new ApiValidationError("questionIds must be an array of saved question ids");
  const ids = [...new Set(value.map((id) => {
    if (typeof id !== "number" || !Number.isSafeInteger(id) || id < 1) throw new ApiValidationError("questionIds must be an array of saved question ids");
    return id;
  }))];
  if (ids.length > MAX_SCHEDULE_QUESTIONS) throw new ApiValidationError(`A schedule can include at most ${MAX_SCHEDULE_QUESTIONS} questions`);
  const visible = await savedQuestionsVisibleTo(actorUserId, ids);
  const kept = new Map((existing ? storedQuestions(existing) : []).filter((item) => item.savedQuestionId !== null).map((item) => [item.savedQuestionId as number, item]));
  return ids.map((id) => {
    const source = visible.get(id);
    if (source) return { savedQuestionId: id, question: source.question, query: source.query };
    const copy = kept.get(id);
    if (copy) return copy;
    throw new ApiValidationError(`Saved question ${id} does not exist or is not visible to you`);
  });
}

type ScheduleValues = Omit<typeof complianceReportSchedules.$inferInsert, "id" | "createdAt" | "updatedAt">;

async function readValues(body: Record<string, unknown>, existing: ScheduleRow | null, actorUserId: number): Promise<ScheduleValues> {
  const name = body.name !== undefined ? parseLine(body.name, "name", 100) : existing ? existing.name : parseLine(body.name, "name", 100);
  const enabled = body.enabled === undefined ? existing?.enabled ?? true : body.enabled;
  if (typeof enabled !== "boolean") throw new ApiValidationError("enabled must be true or false");
  const frequency = body.frequency === undefined ? (existing ? frequencyOf(existing) : "monthly") : body.frequency;
  if (!(FREQUENCIES as readonly unknown[]).includes(frequency)) throw new ApiValidationError("frequency must be weekly or monthly");
  const weekdayRaw = body.weekday === undefined ? existing?.weekday ?? "monday" : body.weekday;
  const weekday = typeof weekdayRaw === "string" ? weekdayRaw.trim().toLowerCase() : weekdayRaw;
  if (frequency === "weekly" && !(WEEKDAYS as readonly unknown[]).includes(weekday)) {
    throw new ApiValidationError(`weekday must be one of: ${WEEKDAYS.join(", ")}`);
  }
  const dayOfMonth = body.dayOfMonth === undefined ? existing?.dayOfMonth ?? 1 : body.dayOfMonth;
  if (frequency === "monthly" && (typeof dayOfMonth !== "number" || !Number.isInteger(dayOfMonth) || dayOfMonth < 1 || dayOfMonth > 28)) {
    throw new ApiValidationError("dayOfMonth must be a whole number from 1 to 28");
  }
  const time = body.time === undefined ? existing?.time ?? "06:00" : typeof body.time === "string" ? body.time.trim() : "";
  if (!TIME.test(time)) throw new ApiValidationError("time must be a time of day as HH:MM (24-hour)");
  const timeZone = body.timeZone === undefined ? existing?.timeZone ?? "UTC" : parseTimeZone(body.timeZone);
  const reportTypes = body.reportTypes === undefined ? (existing ? storedTypes(existing) : [...SELECTABLE_REPORT_TYPES]) : readReportTypes(body.reportTypes);
  const questions = body.questionIds === undefined ? (existing ? storedQuestions(existing) : []) : await readQuestionIds(body.questionIds, existing, actorUserId);
  if (reportTypes.length === 0 && questions.length === 0) {
    throw new ApiValidationError("reportTypes must list at least one report type, or questionIds at least one saved question");
  }
  const channelIds = body.channelIds === undefined ? (existing ? storedChannels(existing) : []) : await readChannelIds(body.channelIds);
  return {
    name,
    enabled,
    frequency: frequency as Frequency,
    weekday: frequency === "weekly" ? (weekday as Weekday) : null,
    dayOfMonth: frequency === "monthly" ? (dayOfMonth as number) : null,
    time,
    timeZone,
    reportTypes: JSON.stringify(reportTypes),
    questions: JSON.stringify(questions),
    channelIds: JSON.stringify(channelIds),
  };
}

function nextRunFor(values: ScheduleValues, now: Date): string | null {
  if (!values.enabled) return null;
  return nextScheduledRun(
    {
      frequency: values.frequency as Frequency,
      weekday: (values.weekday ?? "monday") as Weekday,
      dayOfMonth: values.dayOfMonth ?? 1,
      time: values.time ?? "06:00",
      timeZone: values.timeZone ?? "UTC",
    },
    now
  ).toISOString();
}

function auditData(values: ScheduleValues) {
  return {
    name: values.name,
    enabled: values.enabled,
    frequency: values.frequency,
    weekday: values.weekday,
    dayOfMonth: values.dayOfMonth,
    time: values.time,
    timeZone: values.timeZone,
    reportTypes: JSON.parse(values.reportTypes ?? "[]"),
    questions: storedQuestions({ questions: values.questions ?? "[]" }),
    channelIds: JSON.parse(values.channelIds ?? "[]"),
  };
}

// ── Changes ───────────────────────────────────────────────────────────

/** Needs the compliance_reports feature. */
export async function createReportSchedule(body: unknown, actorUserId: number, now: Date = new Date()): Promise<ReportScheduleView> {
  await requireFeature(FEATURE);
  const record = requireRecord(body);
  rejectUnknownKeys(record, FIELDS, "the report schedule");
  const scheduleCount = async () => (await appDb.select({ id: complianceReportSchedules.id }).from(complianceReportSchedules)).length;
  if (await scheduleCount() >= MAX_SCHEDULES) throw new ApiValidationError(`At most ${MAX_SCHEDULES} report schedules can be set up`);
  const values = await readValues(record, null, actorUserId);
  const stamp = nowIso();
  // Counted again with the insert, in one transaction: the limit holds under concurrent requests.
  const row = await appDb.transaction(async (tx) => {
    if (await scheduleCount() >= MAX_SCHEDULES) throw new ApiValidationError(`At most ${MAX_SCHEDULES} report schedules can be set up`);
    return (await first(tx
      .insert(complianceReportSchedules)
      .values({ ...values, nextRunAt: nextRunFor(values, now), createdBy: actorUserId, createdAt: stamp, updatedAt: stamp })
      .returning()))!;
  });
  await logAuditEvent({
    userId: actorUserId,
    action: "compliance_schedule_created",
    entityType: "compliance_schedule",
    entityId: row.id,
    summary: `Created the ${values.frequency} report schedule "${values.name}"`,
    data: auditData(values),
  });
  return toView(row);
}

/** Disabling needs no license; any other change does. */
export async function updateReportSchedule(id: number, body: unknown, actorUserId: number, now: Date = new Date()): Promise<ReportScheduleView> {
  const existing = await requireRow(id);
  const record = requireRecord(body);
  rejectUnknownKeys(record, FIELDS, "the report schedule");
  if (!isWindDownOnly(record, { enabled: false })) await requireFeature(FEATURE);
  const values = await readValues(record, existing, actorUserId);
  const timingChanged =
    values.enabled !== existing.enabled ||
    values.frequency !== existing.frequency ||
    values.weekday !== existing.weekday ||
    values.dayOfMonth !== existing.dayOfMonth ||
    values.time !== existing.time ||
    values.timeZone !== existing.timeZone;
  const row = (await first(appDb
    .update(complianceReportSchedules)
    .set({ ...values, nextRunAt: timingChanged ? nextRunFor(values, now) : existing.nextRunAt, updatedAt: nowIso() })
    .where(eq(complianceReportSchedules.id, id))
    .returning()))!;
  await logAuditEvent({
    userId: actorUserId,
    action: "compliance_schedule_updated",
    entityType: "compliance_schedule",
    entityId: id,
    summary: values.enabled ? `Updated the report schedule "${values.name}"` : `Disabled the report schedule "${values.name}"`,
    data: auditData(values),
  });
  return toView(row);
}

/** Never needs a license. Reports it generated are kept. */
export async function deleteReportSchedule(id: number, actorUserId: number): Promise<void> {
  const existing = await requireRow(id);
  await appDb.delete(complianceReportSchedules).where(eq(complianceReportSchedules.id, id));
  await logAuditEvent({
    userId: actorUserId,
    action: "compliance_schedule_deleted",
    entityType: "compliance_schedule",
    entityId: id,
    summary: `Deleted the report schedule "${existing.name}"; the reports it generated are kept`,
    data: { name: existing.name },
  });
}

// ── Running ───────────────────────────────────────────────────────────

export type ScheduleRunDependencies = Partial<ReportDependencies> & {
  notice?: NoticeDependencies;
  verifyChain?: typeof verifyAuditChain;
};

export type ScheduleRunResult = {
  packId: string;
  period: { from: string; to: string };
  status: "success" | "partial" | "failed";
  reports: StoredReportSummary[];
  failed: { type: ReportType; error: string }[];
  chain: { ok: boolean; checked: number } | null;
  deliveries: NoticeDelivery[];
};

function dashboardLink(path: string): string | null {
  try {
    return new URL(path, config.baseUrl).toString();
  } catch {
    return null;
  }
}

function day(iso: string): string {
  return iso.slice(0, 10);
}

/** Generates the schedule's reports for `period`, records the chain check and sends the notice. */
async function runSchedule(row: ScheduleRow, period: { from: Date; to: Date }, actorUserId: number | null, deps: ScheduleRunDependencies): Promise<ScheduleRunResult> {
  const packId = randomUUID();
  const questions = storedQuestions(row);
  const types: ReportType[] = [...storedTypes(row), ...(questions.length > 0 ? (["traffic_questions"] as const) : [])];
  const reports: StoredReportSummary[] = [];
  const failed: ScheduleRunResult["failed"] = [];
  const generator = actorUserId === null
    ? { userId: null, name: `Schedule "${row.name}"`, email: null }
    : await (async () => {
        const user = await first(appDb.select({ name: users.name, email: users.email, username: users.username }).from(users).where(eq(users.id, actorUserId)).limit(1));
        return { userId: actorUserId, name: user?.name ?? user?.username ?? null, email: user?.email ?? null };
      })();

  let chain: ScheduleRunResult["chain"] = null;
  try {
    const verification = await (deps.verifyChain ?? verifyAuditChain)();
    chain = { ok: verification.ok, checked: verification.checked };
    await logAuditEvent({
      userId: actorUserId,
      action: "audit_log_verified",
      entityType: "audit_log",
      summary: verification.ok
        ? `Verified the audit log hash chain for the report schedule "${row.name}": ${verification.checked} event${verification.checked === 1 ? "" : "s"} intact`
        : `Verified the audit log hash chain for the report schedule "${row.name}": mismatch at event #${verification.firstMismatchId}`,
      data: { ok: verification.ok, checked: verification.checked, firstMismatchId: verification.firstMismatchId, headId: verification.headId, headHash: verification.headHash, scheduleId: row.id },
    });
  } catch {
    // The reports still go out; the change log report carries its own verification.
  }

  for (const type of types) {
    try {
      const document = await buildReportDocument({ type, from: period.from, to: period.to, questions }, generator, deps);
      reports.push(await storeReportDocument(document, { actorUserId, scheduleId: row.id, packId }));
    } catch (error) {
      failed.push({ type, error: error instanceof Error && error.name !== "Error" ? error.name : "The report could not be generated" });
    }
  }
  const status = failed.length === 0 ? "success" : reports.length === 0 ? "failed" : "partial";
  const at = (deps.now ?? (() => new Date()))().toISOString();
  const findingsLine = (report: StoredReportSummary) => {
    const counts = Object.entries(report.findings).filter(([, value]) => value > 0).map(([severity, value]) => `${value} ${severity}`);
    return `${report.title}: ${counts.length > 0 ? counts.join(", ") : "no findings"} (SHA-256 ${report.sha256.slice(0, 16)}…)`;
  };
  const notice: Notice = {
    event: "compliance_reports_generated",
    title: `${row.name}: evidence for ${day(period.from.toISOString())} to ${day(period.to.toISOString())}`,
    lines: [
      ...reports.map(findingsLine),
      ...failed.map((item) => `${REPORT_TYPE_LABELS[item.type]}: could not be generated`),
      ...(chain ? [chain.ok ? `Audit log hash chain intact: ${chain.checked} events checked.` : "The audit log hash chain does not verify: open the audit log."] : []),
      "Every report is hashed and its SHA-256 recorded in the audit log. Open them in the dashboard; they are not attached here.",
    ],
    link: dashboardLink("/compliance"),
    data: {
      scheduleId: row.id,
      packId,
      period: { from: period.from.toISOString(), to: period.to.toISOString() },
      status,
      reports: reports.map((report) => ({ id: report.id, type: report.type, sha256: report.sha256, findings: report.findings })),
      auditChain: chain,
    },
    at,
  };
  const deliveries = await sendNotice(storedChannels(row), notice, deps.notice).catch(() => [] as NoticeDelivery[]);
  await appDb.update(complianceReportSchedules)
    .set({
      lastRunAt: at,
      lastStatus: status,
      lastError: failed.length > 0 ? failed.map((item) => `${REPORT_TYPE_LABELS[item.type]}: ${item.error}`).join("; ").slice(0, 500) : null,
      lastPackId: packId,
      lastDeliveries: JSON.stringify(deliveries),
    })
    .where(eq(complianceReportSchedules.id, row.id));
  await logAuditEvent({
    userId: actorUserId,
    action: "compliance_evidence_pack_generated",
    entityType: "compliance_schedule",
    entityId: row.id,
    summary: `Report schedule "${row.name}" generated ${reports.length} of ${types.length} report${types.length === 1 ? "" : "s"} for ${day(period.from.toISOString())} to ${day(period.to.toISOString())}`,
    data: {
      packId,
      status,
      reportIds: reports.map((report) => report.id),
      deliveries: deliveries.map(({ channelId, ok }) => ({ channelId, ok })),
    },
  });
  return { packId, period: { from: period.from.toISOString(), to: period.to.toISOString() }, status, reports, failed, chain, deliveries };
}

/** Runs a schedule now, for the period its last due run covered. Needs the compliance_reports feature. */
export async function runReportScheduleNow(id: number, actorUserId: number, deps: ScheduleRunDependencies = {}): Promise<ScheduleRunResult> {
  const row = await requireRow(id);
  await requireFeature(FEATURE);
  const now = (deps.now ?? (() => new Date()))();
  // The period of a run made now: the week or month that has ended.
  return runSchedule(row, periodOfRun(timingOf(row), now), actorUserId, deps);
}

/** Runs every enabled schedule that is due. Never checks the license. */
export async function runDueReportSchedules(now: Date = new Date(), deps: ScheduleRunDependencies = {}): Promise<number> {
  const due = await appDb
    .select()
    .from(complianceReportSchedules)
    .where(and(eq(complianceReportSchedules.enabled, true), isNotNull(complianceReportSchedules.nextRunAt), lte(complianceReportSchedules.nextRunAt, now.toISOString())))
    .orderBy(asc(complianceReportSchedules.nextRunAt), asc(complianceReportSchedules.id));
  let ran = 0;
  for (const row of due) {
    const runAt = new Date(row.nextRunAt!);
    const timing = timingOf(row);
    // Claim the run first, so a slow or failing run is never repeated.
    const claimed = await appDb
      .update(complianceReportSchedules)
      .set({ nextRunAt: nextScheduledRun(timing, now).toISOString() })
      .where(and(eq(complianceReportSchedules.id, row.id), eq(complianceReportSchedules.nextRunAt, row.nextRunAt!)))
      .returning({ id: complianceReportSchedules.id });
    if (claimed.length === 0) continue;
    await runSchedule(row, periodOfRun(timing, runAt), null, { now: () => now, ...deps });
    ran += 1;
  }
  return ran;
}

/** The newest reports a schedule generated, grouped per run (for the compliance page). */
export async function listEvidencePacks(limit = 12): Promise<{ packId: string; scheduleId: number | null; generatedAt: string; reports: StoredReportSummary[] }[]> {
  const rows = await appDb
    .select({ packId: complianceReports.packId, scheduleId: complianceReports.scheduleId, generatedAt: complianceReports.generatedAt })
    .from(complianceReports)
    .where(isNotNull(complianceReports.packId))
    .orderBy(desc(complianceReports.generatedAt), desc(complianceReports.id))
    .limit(limit * REPORT_TYPES.length);
  const packs = new Map<string, { packId: string; scheduleId: number | null; generatedAt: string }>();
  for (const row of rows) {
    if (row.packId && !packs.has(row.packId)) packs.set(row.packId, { packId: row.packId, scheduleId: row.scheduleId, generatedAt: row.generatedAt });
  }
  return Promise.all([...packs.values()].slice(0, limit).map(async (pack) => ({ ...pack, reports: await lastReportsOf(pack.packId) })));
}
